package cn.lby.dao;

import cn.lby.entity.MarketActivityReportWeekAdvertisement;
import cn.lby.entity.MarketActivityReportWeekAdvertisementExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketActivityReportWeekAdvertisementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week_advertisement
     *
     * @mbggenerated
     */
    int countByExample(MarketActivityReportWeekAdvertisementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week_advertisement
     *
     * @mbggenerated
     */
    int deleteByExample(MarketActivityReportWeekAdvertisementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week_advertisement
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week_advertisement
     *
     * @mbggenerated
     */
    int insert(MarketActivityReportWeekAdvertisement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week_advertisement
     *
     * @mbggenerated
     */
    int insertSelective(MarketActivityReportWeekAdvertisement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week_advertisement
     *
     * @mbggenerated
     */
    List<MarketActivityReportWeekAdvertisement> selectByExample(MarketActivityReportWeekAdvertisementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week_advertisement
     *
     * @mbggenerated
     */
    MarketActivityReportWeekAdvertisement selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week_advertisement
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MarketActivityReportWeekAdvertisement record, @Param("example") MarketActivityReportWeekAdvertisementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week_advertisement
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MarketActivityReportWeekAdvertisement record, @Param("example") MarketActivityReportWeekAdvertisementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week_advertisement
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MarketActivityReportWeekAdvertisement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week_advertisement
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MarketActivityReportWeekAdvertisement record);
}