package cn.lby.dao;

import cn.lby.entity.MarketActivityReportWeekClosingVehicle;
import cn.lby.entity.MarketActivityReportWeekClosingVehicleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketActivityReportWeekClosingVehicleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week_closing_vehicle
     *
     * @mbggenerated
     */
    int countByExample(MarketActivityReportWeekClosingVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week_closing_vehicle
     *
     * @mbggenerated
     */
    int deleteByExample(MarketActivityReportWeekClosingVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week_closing_vehicle
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week_closing_vehicle
     *
     * @mbggenerated
     */
    int insert(MarketActivityReportWeekClosingVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week_closing_vehicle
     *
     * @mbggenerated
     */
    int insertSelective(MarketActivityReportWeekClosingVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week_closing_vehicle
     *
     * @mbggenerated
     */
    List<MarketActivityReportWeekClosingVehicle> selectByExample(MarketActivityReportWeekClosingVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week_closing_vehicle
     *
     * @mbggenerated
     */
    MarketActivityReportWeekClosingVehicle selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week_closing_vehicle
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MarketActivityReportWeekClosingVehicle record, @Param("example") MarketActivityReportWeekClosingVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week_closing_vehicle
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MarketActivityReportWeekClosingVehicle record, @Param("example") MarketActivityReportWeekClosingVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week_closing_vehicle
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MarketActivityReportWeekClosingVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week_closing_vehicle
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MarketActivityReportWeekClosingVehicle record);
}