package cn.lby.dao;

import cn.lby.entity.MarketActivityReportWeek;
import cn.lby.entity.MarketActivityReportWeekExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketActivityReportWeekMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week
     *
     * @mbggenerated
     */
    int countByExample(MarketActivityReportWeekExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week
     *
     * @mbggenerated
     */
    int deleteByExample(MarketActivityReportWeekExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week
     *
     * @mbggenerated
     */
    int insert(MarketActivityReportWeek record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week
     *
     * @mbggenerated
     */
    int insertSelective(MarketActivityReportWeek record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week
     *
     * @mbggenerated
     */
    List<MarketActivityReportWeek> selectByExample(MarketActivityReportWeekExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week
     *
     * @mbggenerated
     */
    MarketActivityReportWeek selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MarketActivityReportWeek record, @Param("example") MarketActivityReportWeekExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MarketActivityReportWeek record, @Param("example") MarketActivityReportWeekExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MarketActivityReportWeek record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MarketActivityReportWeek record);
}