package cn.lby.dao;

import cn.lby.entity.RewardRecord;
import cn.lby.entity.RewardRecordExample;

import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface RewardRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reward_record
	 * @mbggenerated
	 */
	int countByExample(RewardRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reward_record
	 * @mbggenerated
	 */
	int deleteByExample(RewardRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reward_record
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reward_record
	 * @mbggenerated
	 */
	int insert(RewardRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reward_record
	 * @mbggenerated
	 */
	int insertSelective(RewardRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reward_record
	 * @mbggenerated
	 */
	List<RewardRecord> selectByExample(RewardRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reward_record
	 * @mbggenerated
	 */
	RewardRecord selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reward_record
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") RewardRecord record,
			@Param("example") RewardRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reward_record
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") RewardRecord record,
			@Param("example") RewardRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reward_record
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(RewardRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reward_record
	 * @mbggenerated
	 */
	int updateByPrimaryKey(RewardRecord record);
	
    /* ------------- lby ------------- */
	List<HashMap<String,Object>> getSatisfactionDegree(String vehicleModelId);

}