package cn.lby.dao;

import cn.lby.entity.SalesRankingQa;
import cn.lby.entity.SalesRankingQaExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface SalesRankingQaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_ranking_qa
     *
     * @mbggenerated
     */
    int countByExample(SalesRankingQaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_ranking_qa
     *
     * @mbggenerated
     */
    int deleteByExample(SalesRankingQaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_ranking_qa
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_ranking_qa
     *
     * @mbggenerated
     */
    int insert(SalesRankingQa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_ranking_qa
     *
     * @mbggenerated
     */
    int insertSelective(SalesRankingQa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_ranking_qa
     *
     * @mbggenerated
     */
    List<SalesRankingQa> selectByExample(SalesRankingQaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_ranking_qa
     *
     * @mbggenerated
     */
    SalesRankingQa selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_ranking_qa
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SalesRankingQa record, @Param("example") SalesRankingQaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_ranking_qa
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SalesRankingQa record, @Param("example") SalesRankingQaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_ranking_qa
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SalesRankingQa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_ranking_qa
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SalesRankingQa record);
    
    /* ----- lby ----- */
    int insertQaWithVehicleModel(Map<String, String> map);

    int insertQa(Map<String, String> map);
}