package cn.lby.dao;

import cn.lby.entity.SalesRecord;
import cn.lby.entity.SalesRecordExample;

import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SalesRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sales_record
	 * @mbggenerated
	 */
	int countByExample(SalesRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sales_record
	 * @mbggenerated
	 */
	int deleteByExample(SalesRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sales_record
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sales_record
	 * @mbggenerated
	 */
	int insert(SalesRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sales_record
	 * @mbggenerated
	 */
	int insertSelective(SalesRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sales_record
	 * @mbggenerated
	 */
	List<SalesRecord> selectByExample(SalesRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sales_record
	 * @mbggenerated
	 */
	SalesRecord selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sales_record
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") SalesRecord record,
			@Param("example") SalesRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sales_record
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") SalesRecord record,
			@Param("example") SalesRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sales_record
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(SalesRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sales_record
	 * @mbggenerated
	 */
	int updateByPrimaryKey(SalesRecord record);
	
    /* --------------- lby ---------------*/
//	List<HashMap<String,Object>> getSalesVolumeRanking(@Param("vehicleModelId") String vehicleModelId,@Param("dealerId") String dealerId);
	List<HashMap<String,Object>> getSalesVolumeRanking(HashMap<String, String> map);

	List<HashMap<String,Object>> getWeekSalesVolumeWithVehicleModel(HashMap<String, String> map);

}