package cn.lby.dao;

import cn.lby.entity.SalesRankingType;
import cn.lby.entity.SalesRankingTypeExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface SalesRankingTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_ranking_type
     *
     * @mbggenerated
     */
    int countByExample(SalesRankingTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_ranking_type
     *
     * @mbggenerated
     */
    int deleteByExample(SalesRankingTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_ranking_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_ranking_type
     *
     * @mbggenerated
     */
    int insert(SalesRankingType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_ranking_type
     *
     * @mbggenerated
     */
    int insertSelective(SalesRankingType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_ranking_type
     *
     * @mbggenerated
     */
    List<SalesRankingType> selectByExample(SalesRankingTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_ranking_type
     *
     * @mbggenerated
     */
    SalesRankingType selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_ranking_type
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SalesRankingType record, @Param("example") SalesRankingTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_ranking_type
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SalesRankingType record, @Param("example") SalesRankingTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_ranking_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SalesRankingType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_ranking_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SalesRankingType record);

    /* ------- lby ------- */
    List<String> selectSalesDate(String dealerId);
    
    int insertTypeWithVehicleModel(Map<String, String> map);
    
    int insertType(Map<String, String> map);

}