package cn.lby.dao;

import cn.lby.entity.TestDriveWeek;
import cn.lby.entity.TestDriveWeekExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestDriveWeekMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_drive_week
     *
     * @mbggenerated
     */
    int countByExample(TestDriveWeekExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_drive_week
     *
     * @mbggenerated
     */
    int deleteByExample(TestDriveWeekExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_drive_week
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_drive_week
     *
     * @mbggenerated
     */
    int insert(TestDriveWeek record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_drive_week
     *
     * @mbggenerated
     */
    int insertSelective(TestDriveWeek record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_drive_week
     *
     * @mbggenerated
     */
    List<TestDriveWeek> selectByExample(TestDriveWeekExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_drive_week
     *
     * @mbggenerated
     */
    TestDriveWeek selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_drive_week
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TestDriveWeek record, @Param("example") TestDriveWeekExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_drive_week
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TestDriveWeek record, @Param("example") TestDriveWeekExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_drive_week
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TestDriveWeek record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_drive_week
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TestDriveWeek record);
}