package cn.lby.entity;

import java.util.Date;

public class AppointmentsReportWeek {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointments_report_week.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointments_report_week.week_start_time
     *
     * @mbggenerated
     */
    private Date weekStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointments_report_week.week_end_time
     *
     * @mbggenerated
     */
    private Date weekEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointments_report_week.dealer_id
     *
     * @mbggenerated
     */
    private String dealerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointments_report_week.dealer_code
     *
     * @mbggenerated
     */
    private String dealerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointments_report_week.dealer_name
     *
     * @mbggenerated
     */
    private String dealerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointments_report_week.market_activity_id
     *
     * @mbggenerated
     */
    private String marketActivityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointments_report_week.market_activity_code
     *
     * @mbggenerated
     */
    private String marketActivityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointments_report_week.market_activity_name
     *
     * @mbggenerated
     */
    private String marketActivityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointments_report_week.num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointments_report_week.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointments_report_week.id
     *
     * @return the value of appointments_report_week.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointments_report_week.id
     *
     * @param id the value for appointments_report_week.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointments_report_week.week_start_time
     *
     * @return the value of appointments_report_week.week_start_time
     *
     * @mbggenerated
     */
    public Date getWeekStartTime() {
        return weekStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointments_report_week.week_start_time
     *
     * @param weekStartTime the value for appointments_report_week.week_start_time
     *
     * @mbggenerated
     */
    public void setWeekStartTime(Date weekStartTime) {
        this.weekStartTime = weekStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointments_report_week.week_end_time
     *
     * @return the value of appointments_report_week.week_end_time
     *
     * @mbggenerated
     */
    public Date getWeekEndTime() {
        return weekEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointments_report_week.week_end_time
     *
     * @param weekEndTime the value for appointments_report_week.week_end_time
     *
     * @mbggenerated
     */
    public void setWeekEndTime(Date weekEndTime) {
        this.weekEndTime = weekEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointments_report_week.dealer_id
     *
     * @return the value of appointments_report_week.dealer_id
     *
     * @mbggenerated
     */
    public String getDealerId() {
        return dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointments_report_week.dealer_id
     *
     * @param dealerId the value for appointments_report_week.dealer_id
     *
     * @mbggenerated
     */
    public void setDealerId(String dealerId) {
        this.dealerId = dealerId == null ? null : dealerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointments_report_week.dealer_code
     *
     * @return the value of appointments_report_week.dealer_code
     *
     * @mbggenerated
     */
    public String getDealerCode() {
        return dealerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointments_report_week.dealer_code
     *
     * @param dealerCode the value for appointments_report_week.dealer_code
     *
     * @mbggenerated
     */
    public void setDealerCode(String dealerCode) {
        this.dealerCode = dealerCode == null ? null : dealerCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointments_report_week.dealer_name
     *
     * @return the value of appointments_report_week.dealer_name
     *
     * @mbggenerated
     */
    public String getDealerName() {
        return dealerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointments_report_week.dealer_name
     *
     * @param dealerName the value for appointments_report_week.dealer_name
     *
     * @mbggenerated
     */
    public void setDealerName(String dealerName) {
        this.dealerName = dealerName == null ? null : dealerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointments_report_week.market_activity_id
     *
     * @return the value of appointments_report_week.market_activity_id
     *
     * @mbggenerated
     */
    public String getMarketActivityId() {
        return marketActivityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointments_report_week.market_activity_id
     *
     * @param marketActivityId the value for appointments_report_week.market_activity_id
     *
     * @mbggenerated
     */
    public void setMarketActivityId(String marketActivityId) {
        this.marketActivityId = marketActivityId == null ? null : marketActivityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointments_report_week.market_activity_code
     *
     * @return the value of appointments_report_week.market_activity_code
     *
     * @mbggenerated
     */
    public String getMarketActivityCode() {
        return marketActivityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointments_report_week.market_activity_code
     *
     * @param marketActivityCode the value for appointments_report_week.market_activity_code
     *
     * @mbggenerated
     */
    public void setMarketActivityCode(String marketActivityCode) {
        this.marketActivityCode = marketActivityCode == null ? null : marketActivityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointments_report_week.market_activity_name
     *
     * @return the value of appointments_report_week.market_activity_name
     *
     * @mbggenerated
     */
    public String getMarketActivityName() {
        return marketActivityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointments_report_week.market_activity_name
     *
     * @param marketActivityName the value for appointments_report_week.market_activity_name
     *
     * @mbggenerated
     */
    public void setMarketActivityName(String marketActivityName) {
        this.marketActivityName = marketActivityName == null ? null : marketActivityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointments_report_week.num
     *
     * @return the value of appointments_report_week.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointments_report_week.num
     *
     * @param num the value for appointments_report_week.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointments_report_week.create_time
     *
     * @return the value of appointments_report_week.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointments_report_week.create_time
     *
     * @param createTime the value for appointments_report_week.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}