package cn.lby.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AppointmentsReportWeekExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table appointments_report_week
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table appointments_report_week
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table appointments_report_week
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointments_report_week
     *
     * @mbggenerated
     */
    public AppointmentsReportWeekExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointments_report_week
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointments_report_week
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointments_report_week
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointments_report_week
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointments_report_week
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointments_report_week
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointments_report_week
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointments_report_week
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointments_report_week
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointments_report_week
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table appointments_report_week
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andWeekStartTimeIsNull() {
            addCriterion("week_start_time is null");
            return (Criteria) this;
        }

        public Criteria andWeekStartTimeIsNotNull() {
            addCriterion("week_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andWeekStartTimeEqualTo(Date value) {
            addCriterion("week_start_time =", value, "weekStartTime");
            return (Criteria) this;
        }

        public Criteria andWeekStartTimeNotEqualTo(Date value) {
            addCriterion("week_start_time <>", value, "weekStartTime");
            return (Criteria) this;
        }

        public Criteria andWeekStartTimeGreaterThan(Date value) {
            addCriterion("week_start_time >", value, "weekStartTime");
            return (Criteria) this;
        }

        public Criteria andWeekStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("week_start_time >=", value, "weekStartTime");
            return (Criteria) this;
        }

        public Criteria andWeekStartTimeLessThan(Date value) {
            addCriterion("week_start_time <", value, "weekStartTime");
            return (Criteria) this;
        }

        public Criteria andWeekStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("week_start_time <=", value, "weekStartTime");
            return (Criteria) this;
        }

        public Criteria andWeekStartTimeIn(List<Date> values) {
            addCriterion("week_start_time in", values, "weekStartTime");
            return (Criteria) this;
        }

        public Criteria andWeekStartTimeNotIn(List<Date> values) {
            addCriterion("week_start_time not in", values, "weekStartTime");
            return (Criteria) this;
        }

        public Criteria andWeekStartTimeBetween(Date value1, Date value2) {
            addCriterion("week_start_time between", value1, value2, "weekStartTime");
            return (Criteria) this;
        }

        public Criteria andWeekStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("week_start_time not between", value1, value2, "weekStartTime");
            return (Criteria) this;
        }

        public Criteria andWeekEndTimeIsNull() {
            addCriterion("week_end_time is null");
            return (Criteria) this;
        }

        public Criteria andWeekEndTimeIsNotNull() {
            addCriterion("week_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andWeekEndTimeEqualTo(Date value) {
            addCriterion("week_end_time =", value, "weekEndTime");
            return (Criteria) this;
        }

        public Criteria andWeekEndTimeNotEqualTo(Date value) {
            addCriterion("week_end_time <>", value, "weekEndTime");
            return (Criteria) this;
        }

        public Criteria andWeekEndTimeGreaterThan(Date value) {
            addCriterion("week_end_time >", value, "weekEndTime");
            return (Criteria) this;
        }

        public Criteria andWeekEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("week_end_time >=", value, "weekEndTime");
            return (Criteria) this;
        }

        public Criteria andWeekEndTimeLessThan(Date value) {
            addCriterion("week_end_time <", value, "weekEndTime");
            return (Criteria) this;
        }

        public Criteria andWeekEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("week_end_time <=", value, "weekEndTime");
            return (Criteria) this;
        }

        public Criteria andWeekEndTimeIn(List<Date> values) {
            addCriterion("week_end_time in", values, "weekEndTime");
            return (Criteria) this;
        }

        public Criteria andWeekEndTimeNotIn(List<Date> values) {
            addCriterion("week_end_time not in", values, "weekEndTime");
            return (Criteria) this;
        }

        public Criteria andWeekEndTimeBetween(Date value1, Date value2) {
            addCriterion("week_end_time between", value1, value2, "weekEndTime");
            return (Criteria) this;
        }

        public Criteria andWeekEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("week_end_time not between", value1, value2, "weekEndTime");
            return (Criteria) this;
        }

        public Criteria andDealerIdIsNull() {
            addCriterion("dealer_id is null");
            return (Criteria) this;
        }

        public Criteria andDealerIdIsNotNull() {
            addCriterion("dealer_id is not null");
            return (Criteria) this;
        }

        public Criteria andDealerIdEqualTo(String value) {
            addCriterion("dealer_id =", value, "dealerId");
            return (Criteria) this;
        }

        public Criteria andDealerIdNotEqualTo(String value) {
            addCriterion("dealer_id <>", value, "dealerId");
            return (Criteria) this;
        }

        public Criteria andDealerIdGreaterThan(String value) {
            addCriterion("dealer_id >", value, "dealerId");
            return (Criteria) this;
        }

        public Criteria andDealerIdGreaterThanOrEqualTo(String value) {
            addCriterion("dealer_id >=", value, "dealerId");
            return (Criteria) this;
        }

        public Criteria andDealerIdLessThan(String value) {
            addCriterion("dealer_id <", value, "dealerId");
            return (Criteria) this;
        }

        public Criteria andDealerIdLessThanOrEqualTo(String value) {
            addCriterion("dealer_id <=", value, "dealerId");
            return (Criteria) this;
        }

        public Criteria andDealerIdLike(String value) {
            addCriterion("dealer_id like", value, "dealerId");
            return (Criteria) this;
        }

        public Criteria andDealerIdNotLike(String value) {
            addCriterion("dealer_id not like", value, "dealerId");
            return (Criteria) this;
        }

        public Criteria andDealerIdIn(List<String> values) {
            addCriterion("dealer_id in", values, "dealerId");
            return (Criteria) this;
        }

        public Criteria andDealerIdNotIn(List<String> values) {
            addCriterion("dealer_id not in", values, "dealerId");
            return (Criteria) this;
        }

        public Criteria andDealerIdBetween(String value1, String value2) {
            addCriterion("dealer_id between", value1, value2, "dealerId");
            return (Criteria) this;
        }

        public Criteria andDealerIdNotBetween(String value1, String value2) {
            addCriterion("dealer_id not between", value1, value2, "dealerId");
            return (Criteria) this;
        }

        public Criteria andDealerCodeIsNull() {
            addCriterion("dealer_code is null");
            return (Criteria) this;
        }

        public Criteria andDealerCodeIsNotNull() {
            addCriterion("dealer_code is not null");
            return (Criteria) this;
        }

        public Criteria andDealerCodeEqualTo(String value) {
            addCriterion("dealer_code =", value, "dealerCode");
            return (Criteria) this;
        }

        public Criteria andDealerCodeNotEqualTo(String value) {
            addCriterion("dealer_code <>", value, "dealerCode");
            return (Criteria) this;
        }

        public Criteria andDealerCodeGreaterThan(String value) {
            addCriterion("dealer_code >", value, "dealerCode");
            return (Criteria) this;
        }

        public Criteria andDealerCodeGreaterThanOrEqualTo(String value) {
            addCriterion("dealer_code >=", value, "dealerCode");
            return (Criteria) this;
        }

        public Criteria andDealerCodeLessThan(String value) {
            addCriterion("dealer_code <", value, "dealerCode");
            return (Criteria) this;
        }

        public Criteria andDealerCodeLessThanOrEqualTo(String value) {
            addCriterion("dealer_code <=", value, "dealerCode");
            return (Criteria) this;
        }

        public Criteria andDealerCodeLike(String value) {
            addCriterion("dealer_code like", value, "dealerCode");
            return (Criteria) this;
        }

        public Criteria andDealerCodeNotLike(String value) {
            addCriterion("dealer_code not like", value, "dealerCode");
            return (Criteria) this;
        }

        public Criteria andDealerCodeIn(List<String> values) {
            addCriterion("dealer_code in", values, "dealerCode");
            return (Criteria) this;
        }

        public Criteria andDealerCodeNotIn(List<String> values) {
            addCriterion("dealer_code not in", values, "dealerCode");
            return (Criteria) this;
        }

        public Criteria andDealerCodeBetween(String value1, String value2) {
            addCriterion("dealer_code between", value1, value2, "dealerCode");
            return (Criteria) this;
        }

        public Criteria andDealerCodeNotBetween(String value1, String value2) {
            addCriterion("dealer_code not between", value1, value2, "dealerCode");
            return (Criteria) this;
        }

        public Criteria andDealerNameIsNull() {
            addCriterion("dealer_name is null");
            return (Criteria) this;
        }

        public Criteria andDealerNameIsNotNull() {
            addCriterion("dealer_name is not null");
            return (Criteria) this;
        }

        public Criteria andDealerNameEqualTo(String value) {
            addCriterion("dealer_name =", value, "dealerName");
            return (Criteria) this;
        }

        public Criteria andDealerNameNotEqualTo(String value) {
            addCriterion("dealer_name <>", value, "dealerName");
            return (Criteria) this;
        }

        public Criteria andDealerNameGreaterThan(String value) {
            addCriterion("dealer_name >", value, "dealerName");
            return (Criteria) this;
        }

        public Criteria andDealerNameGreaterThanOrEqualTo(String value) {
            addCriterion("dealer_name >=", value, "dealerName");
            return (Criteria) this;
        }

        public Criteria andDealerNameLessThan(String value) {
            addCriterion("dealer_name <", value, "dealerName");
            return (Criteria) this;
        }

        public Criteria andDealerNameLessThanOrEqualTo(String value) {
            addCriterion("dealer_name <=", value, "dealerName");
            return (Criteria) this;
        }

        public Criteria andDealerNameLike(String value) {
            addCriterion("dealer_name like", value, "dealerName");
            return (Criteria) this;
        }

        public Criteria andDealerNameNotLike(String value) {
            addCriterion("dealer_name not like", value, "dealerName");
            return (Criteria) this;
        }

        public Criteria andDealerNameIn(List<String> values) {
            addCriterion("dealer_name in", values, "dealerName");
            return (Criteria) this;
        }

        public Criteria andDealerNameNotIn(List<String> values) {
            addCriterion("dealer_name not in", values, "dealerName");
            return (Criteria) this;
        }

        public Criteria andDealerNameBetween(String value1, String value2) {
            addCriterion("dealer_name between", value1, value2, "dealerName");
            return (Criteria) this;
        }

        public Criteria andDealerNameNotBetween(String value1, String value2) {
            addCriterion("dealer_name not between", value1, value2, "dealerName");
            return (Criteria) this;
        }

        public Criteria andMarketActivityIdIsNull() {
            addCriterion("market_activity_id is null");
            return (Criteria) this;
        }

        public Criteria andMarketActivityIdIsNotNull() {
            addCriterion("market_activity_id is not null");
            return (Criteria) this;
        }

        public Criteria andMarketActivityIdEqualTo(String value) {
            addCriterion("market_activity_id =", value, "marketActivityId");
            return (Criteria) this;
        }

        public Criteria andMarketActivityIdNotEqualTo(String value) {
            addCriterion("market_activity_id <>", value, "marketActivityId");
            return (Criteria) this;
        }

        public Criteria andMarketActivityIdGreaterThan(String value) {
            addCriterion("market_activity_id >", value, "marketActivityId");
            return (Criteria) this;
        }

        public Criteria andMarketActivityIdGreaterThanOrEqualTo(String value) {
            addCriterion("market_activity_id >=", value, "marketActivityId");
            return (Criteria) this;
        }

        public Criteria andMarketActivityIdLessThan(String value) {
            addCriterion("market_activity_id <", value, "marketActivityId");
            return (Criteria) this;
        }

        public Criteria andMarketActivityIdLessThanOrEqualTo(String value) {
            addCriterion("market_activity_id <=", value, "marketActivityId");
            return (Criteria) this;
        }

        public Criteria andMarketActivityIdLike(String value) {
            addCriterion("market_activity_id like", value, "marketActivityId");
            return (Criteria) this;
        }

        public Criteria andMarketActivityIdNotLike(String value) {
            addCriterion("market_activity_id not like", value, "marketActivityId");
            return (Criteria) this;
        }

        public Criteria andMarketActivityIdIn(List<String> values) {
            addCriterion("market_activity_id in", values, "marketActivityId");
            return (Criteria) this;
        }

        public Criteria andMarketActivityIdNotIn(List<String> values) {
            addCriterion("market_activity_id not in", values, "marketActivityId");
            return (Criteria) this;
        }

        public Criteria andMarketActivityIdBetween(String value1, String value2) {
            addCriterion("market_activity_id between", value1, value2, "marketActivityId");
            return (Criteria) this;
        }

        public Criteria andMarketActivityIdNotBetween(String value1, String value2) {
            addCriterion("market_activity_id not between", value1, value2, "marketActivityId");
            return (Criteria) this;
        }

        public Criteria andMarketActivityCodeIsNull() {
            addCriterion("market_activity_code is null");
            return (Criteria) this;
        }

        public Criteria andMarketActivityCodeIsNotNull() {
            addCriterion("market_activity_code is not null");
            return (Criteria) this;
        }

        public Criteria andMarketActivityCodeEqualTo(String value) {
            addCriterion("market_activity_code =", value, "marketActivityCode");
            return (Criteria) this;
        }

        public Criteria andMarketActivityCodeNotEqualTo(String value) {
            addCriterion("market_activity_code <>", value, "marketActivityCode");
            return (Criteria) this;
        }

        public Criteria andMarketActivityCodeGreaterThan(String value) {
            addCriterion("market_activity_code >", value, "marketActivityCode");
            return (Criteria) this;
        }

        public Criteria andMarketActivityCodeGreaterThanOrEqualTo(String value) {
            addCriterion("market_activity_code >=", value, "marketActivityCode");
            return (Criteria) this;
        }

        public Criteria andMarketActivityCodeLessThan(String value) {
            addCriterion("market_activity_code <", value, "marketActivityCode");
            return (Criteria) this;
        }

        public Criteria andMarketActivityCodeLessThanOrEqualTo(String value) {
            addCriterion("market_activity_code <=", value, "marketActivityCode");
            return (Criteria) this;
        }

        public Criteria andMarketActivityCodeLike(String value) {
            addCriterion("market_activity_code like", value, "marketActivityCode");
            return (Criteria) this;
        }

        public Criteria andMarketActivityCodeNotLike(String value) {
            addCriterion("market_activity_code not like", value, "marketActivityCode");
            return (Criteria) this;
        }

        public Criteria andMarketActivityCodeIn(List<String> values) {
            addCriterion("market_activity_code in", values, "marketActivityCode");
            return (Criteria) this;
        }

        public Criteria andMarketActivityCodeNotIn(List<String> values) {
            addCriterion("market_activity_code not in", values, "marketActivityCode");
            return (Criteria) this;
        }

        public Criteria andMarketActivityCodeBetween(String value1, String value2) {
            addCriterion("market_activity_code between", value1, value2, "marketActivityCode");
            return (Criteria) this;
        }

        public Criteria andMarketActivityCodeNotBetween(String value1, String value2) {
            addCriterion("market_activity_code not between", value1, value2, "marketActivityCode");
            return (Criteria) this;
        }

        public Criteria andMarketActivityNameIsNull() {
            addCriterion("market_activity_name is null");
            return (Criteria) this;
        }

        public Criteria andMarketActivityNameIsNotNull() {
            addCriterion("market_activity_name is not null");
            return (Criteria) this;
        }

        public Criteria andMarketActivityNameEqualTo(String value) {
            addCriterion("market_activity_name =", value, "marketActivityName");
            return (Criteria) this;
        }

        public Criteria andMarketActivityNameNotEqualTo(String value) {
            addCriterion("market_activity_name <>", value, "marketActivityName");
            return (Criteria) this;
        }

        public Criteria andMarketActivityNameGreaterThan(String value) {
            addCriterion("market_activity_name >", value, "marketActivityName");
            return (Criteria) this;
        }

        public Criteria andMarketActivityNameGreaterThanOrEqualTo(String value) {
            addCriterion("market_activity_name >=", value, "marketActivityName");
            return (Criteria) this;
        }

        public Criteria andMarketActivityNameLessThan(String value) {
            addCriterion("market_activity_name <", value, "marketActivityName");
            return (Criteria) this;
        }

        public Criteria andMarketActivityNameLessThanOrEqualTo(String value) {
            addCriterion("market_activity_name <=", value, "marketActivityName");
            return (Criteria) this;
        }

        public Criteria andMarketActivityNameLike(String value) {
            addCriterion("market_activity_name like", value, "marketActivityName");
            return (Criteria) this;
        }

        public Criteria andMarketActivityNameNotLike(String value) {
            addCriterion("market_activity_name not like", value, "marketActivityName");
            return (Criteria) this;
        }

        public Criteria andMarketActivityNameIn(List<String> values) {
            addCriterion("market_activity_name in", values, "marketActivityName");
            return (Criteria) this;
        }

        public Criteria andMarketActivityNameNotIn(List<String> values) {
            addCriterion("market_activity_name not in", values, "marketActivityName");
            return (Criteria) this;
        }

        public Criteria andMarketActivityNameBetween(String value1, String value2) {
            addCriterion("market_activity_name between", value1, value2, "marketActivityName");
            return (Criteria) this;
        }

        public Criteria andMarketActivityNameNotBetween(String value1, String value2) {
            addCriterion("market_activity_name not between", value1, value2, "marketActivityName");
            return (Criteria) this;
        }

        public Criteria andNumIsNull() {
            addCriterion("num is null");
            return (Criteria) this;
        }

        public Criteria andNumIsNotNull() {
            addCriterion("num is not null");
            return (Criteria) this;
        }

        public Criteria andNumEqualTo(Integer value) {
            addCriterion("num =", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotEqualTo(Integer value) {
            addCriterion("num <>", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThan(Integer value) {
            addCriterion("num >", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("num >=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThan(Integer value) {
            addCriterion("num <", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThanOrEqualTo(Integer value) {
            addCriterion("num <=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumIn(List<Integer> values) {
            addCriterion("num in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotIn(List<Integer> values) {
            addCriterion("num not in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumBetween(Integer value1, Integer value2) {
            addCriterion("num between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotBetween(Integer value1, Integer value2) {
            addCriterion("num not between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table appointments_report_week
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table appointments_report_week
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}