package cn.lby.entity;

import java.util.Date;

public class MarketActivityReportWeekIntention {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week_intention.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week_intention.market_activity_report_week_id
     *
     * @mbggenerated
     */
    private String marketActivityReportWeekId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week_intention.level_of_intent
     *
     * @mbggenerated
     */
    private Integer levelOfIntent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week_intention.vehicle_model_id
     *
     * @mbggenerated
     */
    private String vehicleModelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week_intention.vehicle_model_code
     *
     * @mbggenerated
     */
    private String vehicleModelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week_intention.vehicle_model_name
     *
     * @mbggenerated
     */
    private String vehicleModelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week_intention.customer_num
     *
     * @mbggenerated
     */
    private Integer customerNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week_intention.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week_intention.is_first
     *
     * @mbggenerated
     */
    private Integer isFirst;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week_intention.id
     *
     * @return the value of market_activity_report_week_intention.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week_intention.id
     *
     * @param id the value for market_activity_report_week_intention.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week_intention.market_activity_report_week_id
     *
     * @return the value of market_activity_report_week_intention.market_activity_report_week_id
     *
     * @mbggenerated
     */
    public String getMarketActivityReportWeekId() {
        return marketActivityReportWeekId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week_intention.market_activity_report_week_id
     *
     * @param marketActivityReportWeekId the value for market_activity_report_week_intention.market_activity_report_week_id
     *
     * @mbggenerated
     */
    public void setMarketActivityReportWeekId(String marketActivityReportWeekId) {
        this.marketActivityReportWeekId = marketActivityReportWeekId == null ? null : marketActivityReportWeekId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week_intention.level_of_intent
     *
     * @return the value of market_activity_report_week_intention.level_of_intent
     *
     * @mbggenerated
     */
    public Integer getLevelOfIntent() {
        return levelOfIntent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week_intention.level_of_intent
     *
     * @param levelOfIntent the value for market_activity_report_week_intention.level_of_intent
     *
     * @mbggenerated
     */
    public void setLevelOfIntent(Integer levelOfIntent) {
        this.levelOfIntent = levelOfIntent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week_intention.vehicle_model_id
     *
     * @return the value of market_activity_report_week_intention.vehicle_model_id
     *
     * @mbggenerated
     */
    public String getVehicleModelId() {
        return vehicleModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week_intention.vehicle_model_id
     *
     * @param vehicleModelId the value for market_activity_report_week_intention.vehicle_model_id
     *
     * @mbggenerated
     */
    public void setVehicleModelId(String vehicleModelId) {
        this.vehicleModelId = vehicleModelId == null ? null : vehicleModelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week_intention.vehicle_model_code
     *
     * @return the value of market_activity_report_week_intention.vehicle_model_code
     *
     * @mbggenerated
     */
    public String getVehicleModelCode() {
        return vehicleModelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week_intention.vehicle_model_code
     *
     * @param vehicleModelCode the value for market_activity_report_week_intention.vehicle_model_code
     *
     * @mbggenerated
     */
    public void setVehicleModelCode(String vehicleModelCode) {
        this.vehicleModelCode = vehicleModelCode == null ? null : vehicleModelCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week_intention.vehicle_model_name
     *
     * @return the value of market_activity_report_week_intention.vehicle_model_name
     *
     * @mbggenerated
     */
    public String getVehicleModelName() {
        return vehicleModelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week_intention.vehicle_model_name
     *
     * @param vehicleModelName the value for market_activity_report_week_intention.vehicle_model_name
     *
     * @mbggenerated
     */
    public void setVehicleModelName(String vehicleModelName) {
        this.vehicleModelName = vehicleModelName == null ? null : vehicleModelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week_intention.customer_num
     *
     * @return the value of market_activity_report_week_intention.customer_num
     *
     * @mbggenerated
     */
    public Integer getCustomerNum() {
        return customerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week_intention.customer_num
     *
     * @param customerNum the value for market_activity_report_week_intention.customer_num
     *
     * @mbggenerated
     */
    public void setCustomerNum(Integer customerNum) {
        this.customerNum = customerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week_intention.create_time
     *
     * @return the value of market_activity_report_week_intention.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week_intention.create_time
     *
     * @param createTime the value for market_activity_report_week_intention.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week_intention.is_first
     *
     * @return the value of market_activity_report_week_intention.is_first
     *
     * @mbggenerated
     */
    public Integer getIsFirst() {
        return isFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week_intention.is_first
     *
     * @param isFirst the value for market_activity_report_week_intention.is_first
     *
     * @mbggenerated
     */
    public void setIsFirst(Integer isFirst) {
        this.isFirst = isFirst;
    }
}