package cn.lby.entity;

import java.util.Date;

public class MarketActivityReportWeek {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week.week_start_time
     *
     * @mbggenerated
     */
    private Date weekStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week.week_end_time
     *
     * @mbggenerated
     */
    private Date weekEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week.old_customer_show_num
     *
     * @mbggenerated
     */
    private Integer oldCustomerShowNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week.old_customer_archives_num
     *
     * @mbggenerated
     */
    private Integer oldCustomerArchivesNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week.appointment_into_num_week
     *
     * @mbggenerated
     */
    private Integer appointmentIntoNumWeek;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week.appointment_into_num
     *
     * @mbggenerated
     */
    private Integer appointmentIntoNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week.archives_num_week
     *
     * @mbggenerated
     */
    private Integer archivesNumWeek;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week.archives_num
     *
     * @mbggenerated
     */
    private Integer archivesNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week.closing_num_week
     *
     * @mbggenerated
     */
    private Integer closingNumWeek;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week.closing_num
     *
     * @mbggenerated
     */
    private Integer closingNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week.Market_Activity_Id
     *
     * @mbggenerated
     */
    private String marketActivityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week.Market_Activity_Code
     *
     * @mbggenerated
     */
    private String marketActivityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week.Market_Activity_Name
     *
     * @mbggenerated
     */
    private String marketActivityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week.push_plan_num_week
     *
     * @mbggenerated
     */
    private Integer pushPlanNumWeek;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week.push_actual_num_week
     *
     * @mbggenerated
     */
    private Integer pushActualNumWeek;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week.push_actual_num
     *
     * @mbggenerated
     */
    private Integer pushActualNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week.push_plan_num
     *
     * @mbggenerated
     */
    private Integer pushPlanNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week.dealer_id
     *
     * @mbggenerated
     */
    private String dealerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week.dealer_code
     *
     * @mbggenerated
     */
    private String dealerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week.dealer_name
     *
     * @mbggenerated
     */
    private String dealerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week.isTotal
     *
     * @mbggenerated
     */
    private Integer istotal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week.id
     *
     * @return the value of market_activity_report_week.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week.id
     *
     * @param id the value for market_activity_report_week.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week.week_start_time
     *
     * @return the value of market_activity_report_week.week_start_time
     *
     * @mbggenerated
     */
    public Date getWeekStartTime() {
        return weekStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week.week_start_time
     *
     * @param weekStartTime the value for market_activity_report_week.week_start_time
     *
     * @mbggenerated
     */
    public void setWeekStartTime(Date weekStartTime) {
        this.weekStartTime = weekStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week.week_end_time
     *
     * @return the value of market_activity_report_week.week_end_time
     *
     * @mbggenerated
     */
    public Date getWeekEndTime() {
        return weekEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week.week_end_time
     *
     * @param weekEndTime the value for market_activity_report_week.week_end_time
     *
     * @mbggenerated
     */
    public void setWeekEndTime(Date weekEndTime) {
        this.weekEndTime = weekEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week.create_time
     *
     * @return the value of market_activity_report_week.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week.create_time
     *
     * @param createTime the value for market_activity_report_week.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week.old_customer_show_num
     *
     * @return the value of market_activity_report_week.old_customer_show_num
     *
     * @mbggenerated
     */
    public Integer getOldCustomerShowNum() {
        return oldCustomerShowNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week.old_customer_show_num
     *
     * @param oldCustomerShowNum the value for market_activity_report_week.old_customer_show_num
     *
     * @mbggenerated
     */
    public void setOldCustomerShowNum(Integer oldCustomerShowNum) {
        this.oldCustomerShowNum = oldCustomerShowNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week.old_customer_archives_num
     *
     * @return the value of market_activity_report_week.old_customer_archives_num
     *
     * @mbggenerated
     */
    public Integer getOldCustomerArchivesNum() {
        return oldCustomerArchivesNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week.old_customer_archives_num
     *
     * @param oldCustomerArchivesNum the value for market_activity_report_week.old_customer_archives_num
     *
     * @mbggenerated
     */
    public void setOldCustomerArchivesNum(Integer oldCustomerArchivesNum) {
        this.oldCustomerArchivesNum = oldCustomerArchivesNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week.appointment_into_num_week
     *
     * @return the value of market_activity_report_week.appointment_into_num_week
     *
     * @mbggenerated
     */
    public Integer getAppointmentIntoNumWeek() {
        return appointmentIntoNumWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week.appointment_into_num_week
     *
     * @param appointmentIntoNumWeek the value for market_activity_report_week.appointment_into_num_week
     *
     * @mbggenerated
     */
    public void setAppointmentIntoNumWeek(Integer appointmentIntoNumWeek) {
        this.appointmentIntoNumWeek = appointmentIntoNumWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week.appointment_into_num
     *
     * @return the value of market_activity_report_week.appointment_into_num
     *
     * @mbggenerated
     */
    public Integer getAppointmentIntoNum() {
        return appointmentIntoNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week.appointment_into_num
     *
     * @param appointmentIntoNum the value for market_activity_report_week.appointment_into_num
     *
     * @mbggenerated
     */
    public void setAppointmentIntoNum(Integer appointmentIntoNum) {
        this.appointmentIntoNum = appointmentIntoNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week.archives_num_week
     *
     * @return the value of market_activity_report_week.archives_num_week
     *
     * @mbggenerated
     */
    public Integer getArchivesNumWeek() {
        return archivesNumWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week.archives_num_week
     *
     * @param archivesNumWeek the value for market_activity_report_week.archives_num_week
     *
     * @mbggenerated
     */
    public void setArchivesNumWeek(Integer archivesNumWeek) {
        this.archivesNumWeek = archivesNumWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week.archives_num
     *
     * @return the value of market_activity_report_week.archives_num
     *
     * @mbggenerated
     */
    public Integer getArchivesNum() {
        return archivesNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week.archives_num
     *
     * @param archivesNum the value for market_activity_report_week.archives_num
     *
     * @mbggenerated
     */
    public void setArchivesNum(Integer archivesNum) {
        this.archivesNum = archivesNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week.closing_num_week
     *
     * @return the value of market_activity_report_week.closing_num_week
     *
     * @mbggenerated
     */
    public Integer getClosingNumWeek() {
        return closingNumWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week.closing_num_week
     *
     * @param closingNumWeek the value for market_activity_report_week.closing_num_week
     *
     * @mbggenerated
     */
    public void setClosingNumWeek(Integer closingNumWeek) {
        this.closingNumWeek = closingNumWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week.closing_num
     *
     * @return the value of market_activity_report_week.closing_num
     *
     * @mbggenerated
     */
    public Integer getClosingNum() {
        return closingNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week.closing_num
     *
     * @param closingNum the value for market_activity_report_week.closing_num
     *
     * @mbggenerated
     */
    public void setClosingNum(Integer closingNum) {
        this.closingNum = closingNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week.Market_Activity_Id
     *
     * @return the value of market_activity_report_week.Market_Activity_Id
     *
     * @mbggenerated
     */
    public String getMarketActivityId() {
        return marketActivityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week.Market_Activity_Id
     *
     * @param marketActivityId the value for market_activity_report_week.Market_Activity_Id
     *
     * @mbggenerated
     */
    public void setMarketActivityId(String marketActivityId) {
        this.marketActivityId = marketActivityId == null ? null : marketActivityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week.Market_Activity_Code
     *
     * @return the value of market_activity_report_week.Market_Activity_Code
     *
     * @mbggenerated
     */
    public String getMarketActivityCode() {
        return marketActivityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week.Market_Activity_Code
     *
     * @param marketActivityCode the value for market_activity_report_week.Market_Activity_Code
     *
     * @mbggenerated
     */
    public void setMarketActivityCode(String marketActivityCode) {
        this.marketActivityCode = marketActivityCode == null ? null : marketActivityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week.Market_Activity_Name
     *
     * @return the value of market_activity_report_week.Market_Activity_Name
     *
     * @mbggenerated
     */
    public String getMarketActivityName() {
        return marketActivityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week.Market_Activity_Name
     *
     * @param marketActivityName the value for market_activity_report_week.Market_Activity_Name
     *
     * @mbggenerated
     */
    public void setMarketActivityName(String marketActivityName) {
        this.marketActivityName = marketActivityName == null ? null : marketActivityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week.push_plan_num_week
     *
     * @return the value of market_activity_report_week.push_plan_num_week
     *
     * @mbggenerated
     */
    public Integer getPushPlanNumWeek() {
        return pushPlanNumWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week.push_plan_num_week
     *
     * @param pushPlanNumWeek the value for market_activity_report_week.push_plan_num_week
     *
     * @mbggenerated
     */
    public void setPushPlanNumWeek(Integer pushPlanNumWeek) {
        this.pushPlanNumWeek = pushPlanNumWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week.push_actual_num_week
     *
     * @return the value of market_activity_report_week.push_actual_num_week
     *
     * @mbggenerated
     */
    public Integer getPushActualNumWeek() {
        return pushActualNumWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week.push_actual_num_week
     *
     * @param pushActualNumWeek the value for market_activity_report_week.push_actual_num_week
     *
     * @mbggenerated
     */
    public void setPushActualNumWeek(Integer pushActualNumWeek) {
        this.pushActualNumWeek = pushActualNumWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week.push_actual_num
     *
     * @return the value of market_activity_report_week.push_actual_num
     *
     * @mbggenerated
     */
    public Integer getPushActualNum() {
        return pushActualNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week.push_actual_num
     *
     * @param pushActualNum the value for market_activity_report_week.push_actual_num
     *
     * @mbggenerated
     */
    public void setPushActualNum(Integer pushActualNum) {
        this.pushActualNum = pushActualNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week.push_plan_num
     *
     * @return the value of market_activity_report_week.push_plan_num
     *
     * @mbggenerated
     */
    public Integer getPushPlanNum() {
        return pushPlanNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week.push_plan_num
     *
     * @param pushPlanNum the value for market_activity_report_week.push_plan_num
     *
     * @mbggenerated
     */
    public void setPushPlanNum(Integer pushPlanNum) {
        this.pushPlanNum = pushPlanNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week.dealer_id
     *
     * @return the value of market_activity_report_week.dealer_id
     *
     * @mbggenerated
     */
    public String getDealerId() {
        return dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week.dealer_id
     *
     * @param dealerId the value for market_activity_report_week.dealer_id
     *
     * @mbggenerated
     */
    public void setDealerId(String dealerId) {
        this.dealerId = dealerId == null ? null : dealerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week.dealer_code
     *
     * @return the value of market_activity_report_week.dealer_code
     *
     * @mbggenerated
     */
    public String getDealerCode() {
        return dealerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week.dealer_code
     *
     * @param dealerCode the value for market_activity_report_week.dealer_code
     *
     * @mbggenerated
     */
    public void setDealerCode(String dealerCode) {
        this.dealerCode = dealerCode == null ? null : dealerCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week.dealer_name
     *
     * @return the value of market_activity_report_week.dealer_name
     *
     * @mbggenerated
     */
    public String getDealerName() {
        return dealerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week.dealer_name
     *
     * @param dealerName the value for market_activity_report_week.dealer_name
     *
     * @mbggenerated
     */
    public void setDealerName(String dealerName) {
        this.dealerName = dealerName == null ? null : dealerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week.isTotal
     *
     * @return the value of market_activity_report_week.isTotal
     *
     * @mbggenerated
     */
    public Integer getIstotal() {
        return istotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week.isTotal
     *
     * @param istotal the value for market_activity_report_week.isTotal
     *
     * @mbggenerated
     */
    public void setIstotal(Integer istotal) {
        this.istotal = istotal;
    }
}