package cn.lby.entity;

import java.util.Date;

public class MarketActivityReportWeekAdvertisement {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week_advertisement.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week_advertisement.market_activity_report_week_id
     *
     * @mbggenerated
     */
    private String marketActivityReportWeekId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week_advertisement.channel_name
     *
     * @mbggenerated
     */
    private String channelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week_advertisement.channel
     *
     * @mbggenerated
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week_advertisement.show_num
     *
     * @mbggenerated
     */
    private Integer showNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week_advertisement.archives_num
     *
     * @mbggenerated
     */
    private Integer archivesNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week_advertisement.click_num
     *
     * @mbggenerated
     */
    private Integer clickNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week_advertisement.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week_advertisement.id
     *
     * @return the value of market_activity_report_week_advertisement.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week_advertisement.id
     *
     * @param id the value for market_activity_report_week_advertisement.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week_advertisement.market_activity_report_week_id
     *
     * @return the value of market_activity_report_week_advertisement.market_activity_report_week_id
     *
     * @mbggenerated
     */
    public String getMarketActivityReportWeekId() {
        return marketActivityReportWeekId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week_advertisement.market_activity_report_week_id
     *
     * @param marketActivityReportWeekId the value for market_activity_report_week_advertisement.market_activity_report_week_id
     *
     * @mbggenerated
     */
    public void setMarketActivityReportWeekId(String marketActivityReportWeekId) {
        this.marketActivityReportWeekId = marketActivityReportWeekId == null ? null : marketActivityReportWeekId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week_advertisement.channel_name
     *
     * @return the value of market_activity_report_week_advertisement.channel_name
     *
     * @mbggenerated
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week_advertisement.channel_name
     *
     * @param channelName the value for market_activity_report_week_advertisement.channel_name
     *
     * @mbggenerated
     */
    public void setChannelName(String channelName) {
        this.channelName = channelName == null ? null : channelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week_advertisement.channel
     *
     * @return the value of market_activity_report_week_advertisement.channel
     *
     * @mbggenerated
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week_advertisement.channel
     *
     * @param channel the value for market_activity_report_week_advertisement.channel
     *
     * @mbggenerated
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week_advertisement.show_num
     *
     * @return the value of market_activity_report_week_advertisement.show_num
     *
     * @mbggenerated
     */
    public Integer getShowNum() {
        return showNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week_advertisement.show_num
     *
     * @param showNum the value for market_activity_report_week_advertisement.show_num
     *
     * @mbggenerated
     */
    public void setShowNum(Integer showNum) {
        this.showNum = showNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week_advertisement.archives_num
     *
     * @return the value of market_activity_report_week_advertisement.archives_num
     *
     * @mbggenerated
     */
    public Integer getArchivesNum() {
        return archivesNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week_advertisement.archives_num
     *
     * @param archivesNum the value for market_activity_report_week_advertisement.archives_num
     *
     * @mbggenerated
     */
    public void setArchivesNum(Integer archivesNum) {
        this.archivesNum = archivesNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week_advertisement.click_num
     *
     * @return the value of market_activity_report_week_advertisement.click_num
     *
     * @mbggenerated
     */
    public Integer getClickNum() {
        return clickNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week_advertisement.click_num
     *
     * @param clickNum the value for market_activity_report_week_advertisement.click_num
     *
     * @mbggenerated
     */
    public void setClickNum(Integer clickNum) {
        this.clickNum = clickNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week_advertisement.create_time
     *
     * @return the value of market_activity_report_week_advertisement.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week_advertisement.create_time
     *
     * @param createTime the value for market_activity_report_week_advertisement.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}