package cn.lby.entity;

public class MarketActivityReportWeekClosingIntention {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week_closing_intention.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week_closing_intention.market_activity_report_week_id
     *
     * @mbggenerated
     */
    private String marketActivityReportWeekId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week_closing_intention.level_of_intent
     *
     * @mbggenerated
     */
    private Integer levelOfIntent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week_closing_intention.closing_num_frist
     *
     * @mbggenerated
     */
    private Integer closingNumFrist;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_activity_report_week_closing_intention.num_first
     *
     * @mbggenerated
     */
    private Integer numFirst;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week_closing_intention.id
     *
     * @return the value of market_activity_report_week_closing_intention.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week_closing_intention.id
     *
     * @param id the value for market_activity_report_week_closing_intention.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week_closing_intention.market_activity_report_week_id
     *
     * @return the value of market_activity_report_week_closing_intention.market_activity_report_week_id
     *
     * @mbggenerated
     */
    public String getMarketActivityReportWeekId() {
        return marketActivityReportWeekId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week_closing_intention.market_activity_report_week_id
     *
     * @param marketActivityReportWeekId the value for market_activity_report_week_closing_intention.market_activity_report_week_id
     *
     * @mbggenerated
     */
    public void setMarketActivityReportWeekId(String marketActivityReportWeekId) {
        this.marketActivityReportWeekId = marketActivityReportWeekId == null ? null : marketActivityReportWeekId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week_closing_intention.level_of_intent
     *
     * @return the value of market_activity_report_week_closing_intention.level_of_intent
     *
     * @mbggenerated
     */
    public Integer getLevelOfIntent() {
        return levelOfIntent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week_closing_intention.level_of_intent
     *
     * @param levelOfIntent the value for market_activity_report_week_closing_intention.level_of_intent
     *
     * @mbggenerated
     */
    public void setLevelOfIntent(Integer levelOfIntent) {
        this.levelOfIntent = levelOfIntent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week_closing_intention.closing_num_frist
     *
     * @return the value of market_activity_report_week_closing_intention.closing_num_frist
     *
     * @mbggenerated
     */
    public Integer getClosingNumFrist() {
        return closingNumFrist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week_closing_intention.closing_num_frist
     *
     * @param closingNumFrist the value for market_activity_report_week_closing_intention.closing_num_frist
     *
     * @mbggenerated
     */
    public void setClosingNumFrist(Integer closingNumFrist) {
        this.closingNumFrist = closingNumFrist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_activity_report_week_closing_intention.num_first
     *
     * @return the value of market_activity_report_week_closing_intention.num_first
     *
     * @mbggenerated
     */
    public Integer getNumFirst() {
        return numFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_activity_report_week_closing_intention.num_first
     *
     * @param numFirst the value for market_activity_report_week_closing_intention.num_first
     *
     * @mbggenerated
     */
    public void setNumFirst(Integer numFirst) {
        this.numFirst = numFirst;
    }
}