package cn.lby.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MarketActivityReportWeekExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table market_activity_report_week
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table market_activity_report_week
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table market_activity_report_week
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week
     *
     * @mbggenerated
     */
    public MarketActivityReportWeekExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table market_activity_report_week
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andWeekStartTimeIsNull() {
            addCriterion("week_start_time is null");
            return (Criteria) this;
        }

        public Criteria andWeekStartTimeIsNotNull() {
            addCriterion("week_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andWeekStartTimeEqualTo(Date value) {
            addCriterion("week_start_time =", value, "weekStartTime");
            return (Criteria) this;
        }

        public Criteria andWeekStartTimeNotEqualTo(Date value) {
            addCriterion("week_start_time <>", value, "weekStartTime");
            return (Criteria) this;
        }

        public Criteria andWeekStartTimeGreaterThan(Date value) {
            addCriterion("week_start_time >", value, "weekStartTime");
            return (Criteria) this;
        }

        public Criteria andWeekStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("week_start_time >=", value, "weekStartTime");
            return (Criteria) this;
        }

        public Criteria andWeekStartTimeLessThan(Date value) {
            addCriterion("week_start_time <", value, "weekStartTime");
            return (Criteria) this;
        }

        public Criteria andWeekStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("week_start_time <=", value, "weekStartTime");
            return (Criteria) this;
        }

        public Criteria andWeekStartTimeIn(List<Date> values) {
            addCriterion("week_start_time in", values, "weekStartTime");
            return (Criteria) this;
        }

        public Criteria andWeekStartTimeNotIn(List<Date> values) {
            addCriterion("week_start_time not in", values, "weekStartTime");
            return (Criteria) this;
        }

        public Criteria andWeekStartTimeBetween(Date value1, Date value2) {
            addCriterion("week_start_time between", value1, value2, "weekStartTime");
            return (Criteria) this;
        }

        public Criteria andWeekStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("week_start_time not between", value1, value2, "weekStartTime");
            return (Criteria) this;
        }

        public Criteria andWeekEndTimeIsNull() {
            addCriterion("week_end_time is null");
            return (Criteria) this;
        }

        public Criteria andWeekEndTimeIsNotNull() {
            addCriterion("week_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andWeekEndTimeEqualTo(Date value) {
            addCriterion("week_end_time =", value, "weekEndTime");
            return (Criteria) this;
        }

        public Criteria andWeekEndTimeNotEqualTo(Date value) {
            addCriterion("week_end_time <>", value, "weekEndTime");
            return (Criteria) this;
        }

        public Criteria andWeekEndTimeGreaterThan(Date value) {
            addCriterion("week_end_time >", value, "weekEndTime");
            return (Criteria) this;
        }

        public Criteria andWeekEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("week_end_time >=", value, "weekEndTime");
            return (Criteria) this;
        }

        public Criteria andWeekEndTimeLessThan(Date value) {
            addCriterion("week_end_time <", value, "weekEndTime");
            return (Criteria) this;
        }

        public Criteria andWeekEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("week_end_time <=", value, "weekEndTime");
            return (Criteria) this;
        }

        public Criteria andWeekEndTimeIn(List<Date> values) {
            addCriterion("week_end_time in", values, "weekEndTime");
            return (Criteria) this;
        }

        public Criteria andWeekEndTimeNotIn(List<Date> values) {
            addCriterion("week_end_time not in", values, "weekEndTime");
            return (Criteria) this;
        }

        public Criteria andWeekEndTimeBetween(Date value1, Date value2) {
            addCriterion("week_end_time between", value1, value2, "weekEndTime");
            return (Criteria) this;
        }

        public Criteria andWeekEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("week_end_time not between", value1, value2, "weekEndTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andOldCustomerShowNumIsNull() {
            addCriterion("old_customer_show_num is null");
            return (Criteria) this;
        }

        public Criteria andOldCustomerShowNumIsNotNull() {
            addCriterion("old_customer_show_num is not null");
            return (Criteria) this;
        }

        public Criteria andOldCustomerShowNumEqualTo(Integer value) {
            addCriterion("old_customer_show_num =", value, "oldCustomerShowNum");
            return (Criteria) this;
        }

        public Criteria andOldCustomerShowNumNotEqualTo(Integer value) {
            addCriterion("old_customer_show_num <>", value, "oldCustomerShowNum");
            return (Criteria) this;
        }

        public Criteria andOldCustomerShowNumGreaterThan(Integer value) {
            addCriterion("old_customer_show_num >", value, "oldCustomerShowNum");
            return (Criteria) this;
        }

        public Criteria andOldCustomerShowNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("old_customer_show_num >=", value, "oldCustomerShowNum");
            return (Criteria) this;
        }

        public Criteria andOldCustomerShowNumLessThan(Integer value) {
            addCriterion("old_customer_show_num <", value, "oldCustomerShowNum");
            return (Criteria) this;
        }

        public Criteria andOldCustomerShowNumLessThanOrEqualTo(Integer value) {
            addCriterion("old_customer_show_num <=", value, "oldCustomerShowNum");
            return (Criteria) this;
        }

        public Criteria andOldCustomerShowNumIn(List<Integer> values) {
            addCriterion("old_customer_show_num in", values, "oldCustomerShowNum");
            return (Criteria) this;
        }

        public Criteria andOldCustomerShowNumNotIn(List<Integer> values) {
            addCriterion("old_customer_show_num not in", values, "oldCustomerShowNum");
            return (Criteria) this;
        }

        public Criteria andOldCustomerShowNumBetween(Integer value1, Integer value2) {
            addCriterion("old_customer_show_num between", value1, value2, "oldCustomerShowNum");
            return (Criteria) this;
        }

        public Criteria andOldCustomerShowNumNotBetween(Integer value1, Integer value2) {
            addCriterion("old_customer_show_num not between", value1, value2, "oldCustomerShowNum");
            return (Criteria) this;
        }

        public Criteria andOldCustomerArchivesNumIsNull() {
            addCriterion("old_customer_archives_num is null");
            return (Criteria) this;
        }

        public Criteria andOldCustomerArchivesNumIsNotNull() {
            addCriterion("old_customer_archives_num is not null");
            return (Criteria) this;
        }

        public Criteria andOldCustomerArchivesNumEqualTo(Integer value) {
            addCriterion("old_customer_archives_num =", value, "oldCustomerArchivesNum");
            return (Criteria) this;
        }

        public Criteria andOldCustomerArchivesNumNotEqualTo(Integer value) {
            addCriterion("old_customer_archives_num <>", value, "oldCustomerArchivesNum");
            return (Criteria) this;
        }

        public Criteria andOldCustomerArchivesNumGreaterThan(Integer value) {
            addCriterion("old_customer_archives_num >", value, "oldCustomerArchivesNum");
            return (Criteria) this;
        }

        public Criteria andOldCustomerArchivesNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("old_customer_archives_num >=", value, "oldCustomerArchivesNum");
            return (Criteria) this;
        }

        public Criteria andOldCustomerArchivesNumLessThan(Integer value) {
            addCriterion("old_customer_archives_num <", value, "oldCustomerArchivesNum");
            return (Criteria) this;
        }

        public Criteria andOldCustomerArchivesNumLessThanOrEqualTo(Integer value) {
            addCriterion("old_customer_archives_num <=", value, "oldCustomerArchivesNum");
            return (Criteria) this;
        }

        public Criteria andOldCustomerArchivesNumIn(List<Integer> values) {
            addCriterion("old_customer_archives_num in", values, "oldCustomerArchivesNum");
            return (Criteria) this;
        }

        public Criteria andOldCustomerArchivesNumNotIn(List<Integer> values) {
            addCriterion("old_customer_archives_num not in", values, "oldCustomerArchivesNum");
            return (Criteria) this;
        }

        public Criteria andOldCustomerArchivesNumBetween(Integer value1, Integer value2) {
            addCriterion("old_customer_archives_num between", value1, value2, "oldCustomerArchivesNum");
            return (Criteria) this;
        }

        public Criteria andOldCustomerArchivesNumNotBetween(Integer value1, Integer value2) {
            addCriterion("old_customer_archives_num not between", value1, value2, "oldCustomerArchivesNum");
            return (Criteria) this;
        }

        public Criteria andAppointmentIntoNumWeekIsNull() {
            addCriterion("appointment_into_num_week is null");
            return (Criteria) this;
        }

        public Criteria andAppointmentIntoNumWeekIsNotNull() {
            addCriterion("appointment_into_num_week is not null");
            return (Criteria) this;
        }

        public Criteria andAppointmentIntoNumWeekEqualTo(Integer value) {
            addCriterion("appointment_into_num_week =", value, "appointmentIntoNumWeek");
            return (Criteria) this;
        }

        public Criteria andAppointmentIntoNumWeekNotEqualTo(Integer value) {
            addCriterion("appointment_into_num_week <>", value, "appointmentIntoNumWeek");
            return (Criteria) this;
        }

        public Criteria andAppointmentIntoNumWeekGreaterThan(Integer value) {
            addCriterion("appointment_into_num_week >", value, "appointmentIntoNumWeek");
            return (Criteria) this;
        }

        public Criteria andAppointmentIntoNumWeekGreaterThanOrEqualTo(Integer value) {
            addCriterion("appointment_into_num_week >=", value, "appointmentIntoNumWeek");
            return (Criteria) this;
        }

        public Criteria andAppointmentIntoNumWeekLessThan(Integer value) {
            addCriterion("appointment_into_num_week <", value, "appointmentIntoNumWeek");
            return (Criteria) this;
        }

        public Criteria andAppointmentIntoNumWeekLessThanOrEqualTo(Integer value) {
            addCriterion("appointment_into_num_week <=", value, "appointmentIntoNumWeek");
            return (Criteria) this;
        }

        public Criteria andAppointmentIntoNumWeekIn(List<Integer> values) {
            addCriterion("appointment_into_num_week in", values, "appointmentIntoNumWeek");
            return (Criteria) this;
        }

        public Criteria andAppointmentIntoNumWeekNotIn(List<Integer> values) {
            addCriterion("appointment_into_num_week not in", values, "appointmentIntoNumWeek");
            return (Criteria) this;
        }

        public Criteria andAppointmentIntoNumWeekBetween(Integer value1, Integer value2) {
            addCriterion("appointment_into_num_week between", value1, value2, "appointmentIntoNumWeek");
            return (Criteria) this;
        }

        public Criteria andAppointmentIntoNumWeekNotBetween(Integer value1, Integer value2) {
            addCriterion("appointment_into_num_week not between", value1, value2, "appointmentIntoNumWeek");
            return (Criteria) this;
        }

        public Criteria andAppointmentIntoNumIsNull() {
            addCriterion("appointment_into_num is null");
            return (Criteria) this;
        }

        public Criteria andAppointmentIntoNumIsNotNull() {
            addCriterion("appointment_into_num is not null");
            return (Criteria) this;
        }

        public Criteria andAppointmentIntoNumEqualTo(Integer value) {
            addCriterion("appointment_into_num =", value, "appointmentIntoNum");
            return (Criteria) this;
        }

        public Criteria andAppointmentIntoNumNotEqualTo(Integer value) {
            addCriterion("appointment_into_num <>", value, "appointmentIntoNum");
            return (Criteria) this;
        }

        public Criteria andAppointmentIntoNumGreaterThan(Integer value) {
            addCriterion("appointment_into_num >", value, "appointmentIntoNum");
            return (Criteria) this;
        }

        public Criteria andAppointmentIntoNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("appointment_into_num >=", value, "appointmentIntoNum");
            return (Criteria) this;
        }

        public Criteria andAppointmentIntoNumLessThan(Integer value) {
            addCriterion("appointment_into_num <", value, "appointmentIntoNum");
            return (Criteria) this;
        }

        public Criteria andAppointmentIntoNumLessThanOrEqualTo(Integer value) {
            addCriterion("appointment_into_num <=", value, "appointmentIntoNum");
            return (Criteria) this;
        }

        public Criteria andAppointmentIntoNumIn(List<Integer> values) {
            addCriterion("appointment_into_num in", values, "appointmentIntoNum");
            return (Criteria) this;
        }

        public Criteria andAppointmentIntoNumNotIn(List<Integer> values) {
            addCriterion("appointment_into_num not in", values, "appointmentIntoNum");
            return (Criteria) this;
        }

        public Criteria andAppointmentIntoNumBetween(Integer value1, Integer value2) {
            addCriterion("appointment_into_num between", value1, value2, "appointmentIntoNum");
            return (Criteria) this;
        }

        public Criteria andAppointmentIntoNumNotBetween(Integer value1, Integer value2) {
            addCriterion("appointment_into_num not between", value1, value2, "appointmentIntoNum");
            return (Criteria) this;
        }

        public Criteria andArchivesNumWeekIsNull() {
            addCriterion("archives_num_week is null");
            return (Criteria) this;
        }

        public Criteria andArchivesNumWeekIsNotNull() {
            addCriterion("archives_num_week is not null");
            return (Criteria) this;
        }

        public Criteria andArchivesNumWeekEqualTo(Integer value) {
            addCriterion("archives_num_week =", value, "archivesNumWeek");
            return (Criteria) this;
        }

        public Criteria andArchivesNumWeekNotEqualTo(Integer value) {
            addCriterion("archives_num_week <>", value, "archivesNumWeek");
            return (Criteria) this;
        }

        public Criteria andArchivesNumWeekGreaterThan(Integer value) {
            addCriterion("archives_num_week >", value, "archivesNumWeek");
            return (Criteria) this;
        }

        public Criteria andArchivesNumWeekGreaterThanOrEqualTo(Integer value) {
            addCriterion("archives_num_week >=", value, "archivesNumWeek");
            return (Criteria) this;
        }

        public Criteria andArchivesNumWeekLessThan(Integer value) {
            addCriterion("archives_num_week <", value, "archivesNumWeek");
            return (Criteria) this;
        }

        public Criteria andArchivesNumWeekLessThanOrEqualTo(Integer value) {
            addCriterion("archives_num_week <=", value, "archivesNumWeek");
            return (Criteria) this;
        }

        public Criteria andArchivesNumWeekIn(List<Integer> values) {
            addCriterion("archives_num_week in", values, "archivesNumWeek");
            return (Criteria) this;
        }

        public Criteria andArchivesNumWeekNotIn(List<Integer> values) {
            addCriterion("archives_num_week not in", values, "archivesNumWeek");
            return (Criteria) this;
        }

        public Criteria andArchivesNumWeekBetween(Integer value1, Integer value2) {
            addCriterion("archives_num_week between", value1, value2, "archivesNumWeek");
            return (Criteria) this;
        }

        public Criteria andArchivesNumWeekNotBetween(Integer value1, Integer value2) {
            addCriterion("archives_num_week not between", value1, value2, "archivesNumWeek");
            return (Criteria) this;
        }

        public Criteria andArchivesNumIsNull() {
            addCriterion("archives_num is null");
            return (Criteria) this;
        }

        public Criteria andArchivesNumIsNotNull() {
            addCriterion("archives_num is not null");
            return (Criteria) this;
        }

        public Criteria andArchivesNumEqualTo(Integer value) {
            addCriterion("archives_num =", value, "archivesNum");
            return (Criteria) this;
        }

        public Criteria andArchivesNumNotEqualTo(Integer value) {
            addCriterion("archives_num <>", value, "archivesNum");
            return (Criteria) this;
        }

        public Criteria andArchivesNumGreaterThan(Integer value) {
            addCriterion("archives_num >", value, "archivesNum");
            return (Criteria) this;
        }

        public Criteria andArchivesNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("archives_num >=", value, "archivesNum");
            return (Criteria) this;
        }

        public Criteria andArchivesNumLessThan(Integer value) {
            addCriterion("archives_num <", value, "archivesNum");
            return (Criteria) this;
        }

        public Criteria andArchivesNumLessThanOrEqualTo(Integer value) {
            addCriterion("archives_num <=", value, "archivesNum");
            return (Criteria) this;
        }

        public Criteria andArchivesNumIn(List<Integer> values) {
            addCriterion("archives_num in", values, "archivesNum");
            return (Criteria) this;
        }

        public Criteria andArchivesNumNotIn(List<Integer> values) {
            addCriterion("archives_num not in", values, "archivesNum");
            return (Criteria) this;
        }

        public Criteria andArchivesNumBetween(Integer value1, Integer value2) {
            addCriterion("archives_num between", value1, value2, "archivesNum");
            return (Criteria) this;
        }

        public Criteria andArchivesNumNotBetween(Integer value1, Integer value2) {
            addCriterion("archives_num not between", value1, value2, "archivesNum");
            return (Criteria) this;
        }

        public Criteria andClosingNumWeekIsNull() {
            addCriterion("closing_num_week is null");
            return (Criteria) this;
        }

        public Criteria andClosingNumWeekIsNotNull() {
            addCriterion("closing_num_week is not null");
            return (Criteria) this;
        }

        public Criteria andClosingNumWeekEqualTo(Integer value) {
            addCriterion("closing_num_week =", value, "closingNumWeek");
            return (Criteria) this;
        }

        public Criteria andClosingNumWeekNotEqualTo(Integer value) {
            addCriterion("closing_num_week <>", value, "closingNumWeek");
            return (Criteria) this;
        }

        public Criteria andClosingNumWeekGreaterThan(Integer value) {
            addCriterion("closing_num_week >", value, "closingNumWeek");
            return (Criteria) this;
        }

        public Criteria andClosingNumWeekGreaterThanOrEqualTo(Integer value) {
            addCriterion("closing_num_week >=", value, "closingNumWeek");
            return (Criteria) this;
        }

        public Criteria andClosingNumWeekLessThan(Integer value) {
            addCriterion("closing_num_week <", value, "closingNumWeek");
            return (Criteria) this;
        }

        public Criteria andClosingNumWeekLessThanOrEqualTo(Integer value) {
            addCriterion("closing_num_week <=", value, "closingNumWeek");
            return (Criteria) this;
        }

        public Criteria andClosingNumWeekIn(List<Integer> values) {
            addCriterion("closing_num_week in", values, "closingNumWeek");
            return (Criteria) this;
        }

        public Criteria andClosingNumWeekNotIn(List<Integer> values) {
            addCriterion("closing_num_week not in", values, "closingNumWeek");
            return (Criteria) this;
        }

        public Criteria andClosingNumWeekBetween(Integer value1, Integer value2) {
            addCriterion("closing_num_week between", value1, value2, "closingNumWeek");
            return (Criteria) this;
        }

        public Criteria andClosingNumWeekNotBetween(Integer value1, Integer value2) {
            addCriterion("closing_num_week not between", value1, value2, "closingNumWeek");
            return (Criteria) this;
        }

        public Criteria andClosingNumIsNull() {
            addCriterion("closing_num is null");
            return (Criteria) this;
        }

        public Criteria andClosingNumIsNotNull() {
            addCriterion("closing_num is not null");
            return (Criteria) this;
        }

        public Criteria andClosingNumEqualTo(Integer value) {
            addCriterion("closing_num =", value, "closingNum");
            return (Criteria) this;
        }

        public Criteria andClosingNumNotEqualTo(Integer value) {
            addCriterion("closing_num <>", value, "closingNum");
            return (Criteria) this;
        }

        public Criteria andClosingNumGreaterThan(Integer value) {
            addCriterion("closing_num >", value, "closingNum");
            return (Criteria) this;
        }

        public Criteria andClosingNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("closing_num >=", value, "closingNum");
            return (Criteria) this;
        }

        public Criteria andClosingNumLessThan(Integer value) {
            addCriterion("closing_num <", value, "closingNum");
            return (Criteria) this;
        }

        public Criteria andClosingNumLessThanOrEqualTo(Integer value) {
            addCriterion("closing_num <=", value, "closingNum");
            return (Criteria) this;
        }

        public Criteria andClosingNumIn(List<Integer> values) {
            addCriterion("closing_num in", values, "closingNum");
            return (Criteria) this;
        }

        public Criteria andClosingNumNotIn(List<Integer> values) {
            addCriterion("closing_num not in", values, "closingNum");
            return (Criteria) this;
        }

        public Criteria andClosingNumBetween(Integer value1, Integer value2) {
            addCriterion("closing_num between", value1, value2, "closingNum");
            return (Criteria) this;
        }

        public Criteria andClosingNumNotBetween(Integer value1, Integer value2) {
            addCriterion("closing_num not between", value1, value2, "closingNum");
            return (Criteria) this;
        }

        public Criteria andMarketActivityIdIsNull() {
            addCriterion("Market_Activity_Id is null");
            return (Criteria) this;
        }

        public Criteria andMarketActivityIdIsNotNull() {
            addCriterion("Market_Activity_Id is not null");
            return (Criteria) this;
        }

        public Criteria andMarketActivityIdEqualTo(String value) {
            addCriterion("Market_Activity_Id =", value, "marketActivityId");
            return (Criteria) this;
        }

        public Criteria andMarketActivityIdNotEqualTo(String value) {
            addCriterion("Market_Activity_Id <>", value, "marketActivityId");
            return (Criteria) this;
        }

        public Criteria andMarketActivityIdGreaterThan(String value) {
            addCriterion("Market_Activity_Id >", value, "marketActivityId");
            return (Criteria) this;
        }

        public Criteria andMarketActivityIdGreaterThanOrEqualTo(String value) {
            addCriterion("Market_Activity_Id >=", value, "marketActivityId");
            return (Criteria) this;
        }

        public Criteria andMarketActivityIdLessThan(String value) {
            addCriterion("Market_Activity_Id <", value, "marketActivityId");
            return (Criteria) this;
        }

        public Criteria andMarketActivityIdLessThanOrEqualTo(String value) {
            addCriterion("Market_Activity_Id <=", value, "marketActivityId");
            return (Criteria) this;
        }

        public Criteria andMarketActivityIdLike(String value) {
            addCriterion("Market_Activity_Id like", value, "marketActivityId");
            return (Criteria) this;
        }

        public Criteria andMarketActivityIdNotLike(String value) {
            addCriterion("Market_Activity_Id not like", value, "marketActivityId");
            return (Criteria) this;
        }

        public Criteria andMarketActivityIdIn(List<String> values) {
            addCriterion("Market_Activity_Id in", values, "marketActivityId");
            return (Criteria) this;
        }

        public Criteria andMarketActivityIdNotIn(List<String> values) {
            addCriterion("Market_Activity_Id not in", values, "marketActivityId");
            return (Criteria) this;
        }

        public Criteria andMarketActivityIdBetween(String value1, String value2) {
            addCriterion("Market_Activity_Id between", value1, value2, "marketActivityId");
            return (Criteria) this;
        }

        public Criteria andMarketActivityIdNotBetween(String value1, String value2) {
            addCriterion("Market_Activity_Id not between", value1, value2, "marketActivityId");
            return (Criteria) this;
        }

        public Criteria andMarketActivityCodeIsNull() {
            addCriterion("Market_Activity_Code is null");
            return (Criteria) this;
        }

        public Criteria andMarketActivityCodeIsNotNull() {
            addCriterion("Market_Activity_Code is not null");
            return (Criteria) this;
        }

        public Criteria andMarketActivityCodeEqualTo(String value) {
            addCriterion("Market_Activity_Code =", value, "marketActivityCode");
            return (Criteria) this;
        }

        public Criteria andMarketActivityCodeNotEqualTo(String value) {
            addCriterion("Market_Activity_Code <>", value, "marketActivityCode");
            return (Criteria) this;
        }

        public Criteria andMarketActivityCodeGreaterThan(String value) {
            addCriterion("Market_Activity_Code >", value, "marketActivityCode");
            return (Criteria) this;
        }

        public Criteria andMarketActivityCodeGreaterThanOrEqualTo(String value) {
            addCriterion("Market_Activity_Code >=", value, "marketActivityCode");
            return (Criteria) this;
        }

        public Criteria andMarketActivityCodeLessThan(String value) {
            addCriterion("Market_Activity_Code <", value, "marketActivityCode");
            return (Criteria) this;
        }

        public Criteria andMarketActivityCodeLessThanOrEqualTo(String value) {
            addCriterion("Market_Activity_Code <=", value, "marketActivityCode");
            return (Criteria) this;
        }

        public Criteria andMarketActivityCodeLike(String value) {
            addCriterion("Market_Activity_Code like", value, "marketActivityCode");
            return (Criteria) this;
        }

        public Criteria andMarketActivityCodeNotLike(String value) {
            addCriterion("Market_Activity_Code not like", value, "marketActivityCode");
            return (Criteria) this;
        }

        public Criteria andMarketActivityCodeIn(List<String> values) {
            addCriterion("Market_Activity_Code in", values, "marketActivityCode");
            return (Criteria) this;
        }

        public Criteria andMarketActivityCodeNotIn(List<String> values) {
            addCriterion("Market_Activity_Code not in", values, "marketActivityCode");
            return (Criteria) this;
        }

        public Criteria andMarketActivityCodeBetween(String value1, String value2) {
            addCriterion("Market_Activity_Code between", value1, value2, "marketActivityCode");
            return (Criteria) this;
        }

        public Criteria andMarketActivityCodeNotBetween(String value1, String value2) {
            addCriterion("Market_Activity_Code not between", value1, value2, "marketActivityCode");
            return (Criteria) this;
        }

        public Criteria andMarketActivityNameIsNull() {
            addCriterion("Market_Activity_Name is null");
            return (Criteria) this;
        }

        public Criteria andMarketActivityNameIsNotNull() {
            addCriterion("Market_Activity_Name is not null");
            return (Criteria) this;
        }

        public Criteria andMarketActivityNameEqualTo(String value) {
            addCriterion("Market_Activity_Name =", value, "marketActivityName");
            return (Criteria) this;
        }

        public Criteria andMarketActivityNameNotEqualTo(String value) {
            addCriterion("Market_Activity_Name <>", value, "marketActivityName");
            return (Criteria) this;
        }

        public Criteria andMarketActivityNameGreaterThan(String value) {
            addCriterion("Market_Activity_Name >", value, "marketActivityName");
            return (Criteria) this;
        }

        public Criteria andMarketActivityNameGreaterThanOrEqualTo(String value) {
            addCriterion("Market_Activity_Name >=", value, "marketActivityName");
            return (Criteria) this;
        }

        public Criteria andMarketActivityNameLessThan(String value) {
            addCriterion("Market_Activity_Name <", value, "marketActivityName");
            return (Criteria) this;
        }

        public Criteria andMarketActivityNameLessThanOrEqualTo(String value) {
            addCriterion("Market_Activity_Name <=", value, "marketActivityName");
            return (Criteria) this;
        }

        public Criteria andMarketActivityNameLike(String value) {
            addCriterion("Market_Activity_Name like", value, "marketActivityName");
            return (Criteria) this;
        }

        public Criteria andMarketActivityNameNotLike(String value) {
            addCriterion("Market_Activity_Name not like", value, "marketActivityName");
            return (Criteria) this;
        }

        public Criteria andMarketActivityNameIn(List<String> values) {
            addCriterion("Market_Activity_Name in", values, "marketActivityName");
            return (Criteria) this;
        }

        public Criteria andMarketActivityNameNotIn(List<String> values) {
            addCriterion("Market_Activity_Name not in", values, "marketActivityName");
            return (Criteria) this;
        }

        public Criteria andMarketActivityNameBetween(String value1, String value2) {
            addCriterion("Market_Activity_Name between", value1, value2, "marketActivityName");
            return (Criteria) this;
        }

        public Criteria andMarketActivityNameNotBetween(String value1, String value2) {
            addCriterion("Market_Activity_Name not between", value1, value2, "marketActivityName");
            return (Criteria) this;
        }

        public Criteria andPushPlanNumWeekIsNull() {
            addCriterion("push_plan_num_week is null");
            return (Criteria) this;
        }

        public Criteria andPushPlanNumWeekIsNotNull() {
            addCriterion("push_plan_num_week is not null");
            return (Criteria) this;
        }

        public Criteria andPushPlanNumWeekEqualTo(Integer value) {
            addCriterion("push_plan_num_week =", value, "pushPlanNumWeek");
            return (Criteria) this;
        }

        public Criteria andPushPlanNumWeekNotEqualTo(Integer value) {
            addCriterion("push_plan_num_week <>", value, "pushPlanNumWeek");
            return (Criteria) this;
        }

        public Criteria andPushPlanNumWeekGreaterThan(Integer value) {
            addCriterion("push_plan_num_week >", value, "pushPlanNumWeek");
            return (Criteria) this;
        }

        public Criteria andPushPlanNumWeekGreaterThanOrEqualTo(Integer value) {
            addCriterion("push_plan_num_week >=", value, "pushPlanNumWeek");
            return (Criteria) this;
        }

        public Criteria andPushPlanNumWeekLessThan(Integer value) {
            addCriterion("push_plan_num_week <", value, "pushPlanNumWeek");
            return (Criteria) this;
        }

        public Criteria andPushPlanNumWeekLessThanOrEqualTo(Integer value) {
            addCriterion("push_plan_num_week <=", value, "pushPlanNumWeek");
            return (Criteria) this;
        }

        public Criteria andPushPlanNumWeekIn(List<Integer> values) {
            addCriterion("push_plan_num_week in", values, "pushPlanNumWeek");
            return (Criteria) this;
        }

        public Criteria andPushPlanNumWeekNotIn(List<Integer> values) {
            addCriterion("push_plan_num_week not in", values, "pushPlanNumWeek");
            return (Criteria) this;
        }

        public Criteria andPushPlanNumWeekBetween(Integer value1, Integer value2) {
            addCriterion("push_plan_num_week between", value1, value2, "pushPlanNumWeek");
            return (Criteria) this;
        }

        public Criteria andPushPlanNumWeekNotBetween(Integer value1, Integer value2) {
            addCriterion("push_plan_num_week not between", value1, value2, "pushPlanNumWeek");
            return (Criteria) this;
        }

        public Criteria andPushActualNumWeekIsNull() {
            addCriterion("push_actual_num_week is null");
            return (Criteria) this;
        }

        public Criteria andPushActualNumWeekIsNotNull() {
            addCriterion("push_actual_num_week is not null");
            return (Criteria) this;
        }

        public Criteria andPushActualNumWeekEqualTo(Integer value) {
            addCriterion("push_actual_num_week =", value, "pushActualNumWeek");
            return (Criteria) this;
        }

        public Criteria andPushActualNumWeekNotEqualTo(Integer value) {
            addCriterion("push_actual_num_week <>", value, "pushActualNumWeek");
            return (Criteria) this;
        }

        public Criteria andPushActualNumWeekGreaterThan(Integer value) {
            addCriterion("push_actual_num_week >", value, "pushActualNumWeek");
            return (Criteria) this;
        }

        public Criteria andPushActualNumWeekGreaterThanOrEqualTo(Integer value) {
            addCriterion("push_actual_num_week >=", value, "pushActualNumWeek");
            return (Criteria) this;
        }

        public Criteria andPushActualNumWeekLessThan(Integer value) {
            addCriterion("push_actual_num_week <", value, "pushActualNumWeek");
            return (Criteria) this;
        }

        public Criteria andPushActualNumWeekLessThanOrEqualTo(Integer value) {
            addCriterion("push_actual_num_week <=", value, "pushActualNumWeek");
            return (Criteria) this;
        }

        public Criteria andPushActualNumWeekIn(List<Integer> values) {
            addCriterion("push_actual_num_week in", values, "pushActualNumWeek");
            return (Criteria) this;
        }

        public Criteria andPushActualNumWeekNotIn(List<Integer> values) {
            addCriterion("push_actual_num_week not in", values, "pushActualNumWeek");
            return (Criteria) this;
        }

        public Criteria andPushActualNumWeekBetween(Integer value1, Integer value2) {
            addCriterion("push_actual_num_week between", value1, value2, "pushActualNumWeek");
            return (Criteria) this;
        }

        public Criteria andPushActualNumWeekNotBetween(Integer value1, Integer value2) {
            addCriterion("push_actual_num_week not between", value1, value2, "pushActualNumWeek");
            return (Criteria) this;
        }

        public Criteria andPushActualNumIsNull() {
            addCriterion("push_actual_num is null");
            return (Criteria) this;
        }

        public Criteria andPushActualNumIsNotNull() {
            addCriterion("push_actual_num is not null");
            return (Criteria) this;
        }

        public Criteria andPushActualNumEqualTo(Integer value) {
            addCriterion("push_actual_num =", value, "pushActualNum");
            return (Criteria) this;
        }

        public Criteria andPushActualNumNotEqualTo(Integer value) {
            addCriterion("push_actual_num <>", value, "pushActualNum");
            return (Criteria) this;
        }

        public Criteria andPushActualNumGreaterThan(Integer value) {
            addCriterion("push_actual_num >", value, "pushActualNum");
            return (Criteria) this;
        }

        public Criteria andPushActualNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("push_actual_num >=", value, "pushActualNum");
            return (Criteria) this;
        }

        public Criteria andPushActualNumLessThan(Integer value) {
            addCriterion("push_actual_num <", value, "pushActualNum");
            return (Criteria) this;
        }

        public Criteria andPushActualNumLessThanOrEqualTo(Integer value) {
            addCriterion("push_actual_num <=", value, "pushActualNum");
            return (Criteria) this;
        }

        public Criteria andPushActualNumIn(List<Integer> values) {
            addCriterion("push_actual_num in", values, "pushActualNum");
            return (Criteria) this;
        }

        public Criteria andPushActualNumNotIn(List<Integer> values) {
            addCriterion("push_actual_num not in", values, "pushActualNum");
            return (Criteria) this;
        }

        public Criteria andPushActualNumBetween(Integer value1, Integer value2) {
            addCriterion("push_actual_num between", value1, value2, "pushActualNum");
            return (Criteria) this;
        }

        public Criteria andPushActualNumNotBetween(Integer value1, Integer value2) {
            addCriterion("push_actual_num not between", value1, value2, "pushActualNum");
            return (Criteria) this;
        }

        public Criteria andPushPlanNumIsNull() {
            addCriterion("push_plan_num is null");
            return (Criteria) this;
        }

        public Criteria andPushPlanNumIsNotNull() {
            addCriterion("push_plan_num is not null");
            return (Criteria) this;
        }

        public Criteria andPushPlanNumEqualTo(Integer value) {
            addCriterion("push_plan_num =", value, "pushPlanNum");
            return (Criteria) this;
        }

        public Criteria andPushPlanNumNotEqualTo(Integer value) {
            addCriterion("push_plan_num <>", value, "pushPlanNum");
            return (Criteria) this;
        }

        public Criteria andPushPlanNumGreaterThan(Integer value) {
            addCriterion("push_plan_num >", value, "pushPlanNum");
            return (Criteria) this;
        }

        public Criteria andPushPlanNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("push_plan_num >=", value, "pushPlanNum");
            return (Criteria) this;
        }

        public Criteria andPushPlanNumLessThan(Integer value) {
            addCriterion("push_plan_num <", value, "pushPlanNum");
            return (Criteria) this;
        }

        public Criteria andPushPlanNumLessThanOrEqualTo(Integer value) {
            addCriterion("push_plan_num <=", value, "pushPlanNum");
            return (Criteria) this;
        }

        public Criteria andPushPlanNumIn(List<Integer> values) {
            addCriterion("push_plan_num in", values, "pushPlanNum");
            return (Criteria) this;
        }

        public Criteria andPushPlanNumNotIn(List<Integer> values) {
            addCriterion("push_plan_num not in", values, "pushPlanNum");
            return (Criteria) this;
        }

        public Criteria andPushPlanNumBetween(Integer value1, Integer value2) {
            addCriterion("push_plan_num between", value1, value2, "pushPlanNum");
            return (Criteria) this;
        }

        public Criteria andPushPlanNumNotBetween(Integer value1, Integer value2) {
            addCriterion("push_plan_num not between", value1, value2, "pushPlanNum");
            return (Criteria) this;
        }

        public Criteria andDealerIdIsNull() {
            addCriterion("dealer_id is null");
            return (Criteria) this;
        }

        public Criteria andDealerIdIsNotNull() {
            addCriterion("dealer_id is not null");
            return (Criteria) this;
        }

        public Criteria andDealerIdEqualTo(String value) {
            addCriterion("dealer_id =", value, "dealerId");
            return (Criteria) this;
        }

        public Criteria andDealerIdNotEqualTo(String value) {
            addCriterion("dealer_id <>", value, "dealerId");
            return (Criteria) this;
        }

        public Criteria andDealerIdGreaterThan(String value) {
            addCriterion("dealer_id >", value, "dealerId");
            return (Criteria) this;
        }

        public Criteria andDealerIdGreaterThanOrEqualTo(String value) {
            addCriterion("dealer_id >=", value, "dealerId");
            return (Criteria) this;
        }

        public Criteria andDealerIdLessThan(String value) {
            addCriterion("dealer_id <", value, "dealerId");
            return (Criteria) this;
        }

        public Criteria andDealerIdLessThanOrEqualTo(String value) {
            addCriterion("dealer_id <=", value, "dealerId");
            return (Criteria) this;
        }

        public Criteria andDealerIdLike(String value) {
            addCriterion("dealer_id like", value, "dealerId");
            return (Criteria) this;
        }

        public Criteria andDealerIdNotLike(String value) {
            addCriterion("dealer_id not like", value, "dealerId");
            return (Criteria) this;
        }

        public Criteria andDealerIdIn(List<String> values) {
            addCriterion("dealer_id in", values, "dealerId");
            return (Criteria) this;
        }

        public Criteria andDealerIdNotIn(List<String> values) {
            addCriterion("dealer_id not in", values, "dealerId");
            return (Criteria) this;
        }

        public Criteria andDealerIdBetween(String value1, String value2) {
            addCriterion("dealer_id between", value1, value2, "dealerId");
            return (Criteria) this;
        }

        public Criteria andDealerIdNotBetween(String value1, String value2) {
            addCriterion("dealer_id not between", value1, value2, "dealerId");
            return (Criteria) this;
        }

        public Criteria andDealerCodeIsNull() {
            addCriterion("dealer_code is null");
            return (Criteria) this;
        }

        public Criteria andDealerCodeIsNotNull() {
            addCriterion("dealer_code is not null");
            return (Criteria) this;
        }

        public Criteria andDealerCodeEqualTo(String value) {
            addCriterion("dealer_code =", value, "dealerCode");
            return (Criteria) this;
        }

        public Criteria andDealerCodeNotEqualTo(String value) {
            addCriterion("dealer_code <>", value, "dealerCode");
            return (Criteria) this;
        }

        public Criteria andDealerCodeGreaterThan(String value) {
            addCriterion("dealer_code >", value, "dealerCode");
            return (Criteria) this;
        }

        public Criteria andDealerCodeGreaterThanOrEqualTo(String value) {
            addCriterion("dealer_code >=", value, "dealerCode");
            return (Criteria) this;
        }

        public Criteria andDealerCodeLessThan(String value) {
            addCriterion("dealer_code <", value, "dealerCode");
            return (Criteria) this;
        }

        public Criteria andDealerCodeLessThanOrEqualTo(String value) {
            addCriterion("dealer_code <=", value, "dealerCode");
            return (Criteria) this;
        }

        public Criteria andDealerCodeLike(String value) {
            addCriterion("dealer_code like", value, "dealerCode");
            return (Criteria) this;
        }

        public Criteria andDealerCodeNotLike(String value) {
            addCriterion("dealer_code not like", value, "dealerCode");
            return (Criteria) this;
        }

        public Criteria andDealerCodeIn(List<String> values) {
            addCriterion("dealer_code in", values, "dealerCode");
            return (Criteria) this;
        }

        public Criteria andDealerCodeNotIn(List<String> values) {
            addCriterion("dealer_code not in", values, "dealerCode");
            return (Criteria) this;
        }

        public Criteria andDealerCodeBetween(String value1, String value2) {
            addCriterion("dealer_code between", value1, value2, "dealerCode");
            return (Criteria) this;
        }

        public Criteria andDealerCodeNotBetween(String value1, String value2) {
            addCriterion("dealer_code not between", value1, value2, "dealerCode");
            return (Criteria) this;
        }

        public Criteria andDealerNameIsNull() {
            addCriterion("dealer_name is null");
            return (Criteria) this;
        }

        public Criteria andDealerNameIsNotNull() {
            addCriterion("dealer_name is not null");
            return (Criteria) this;
        }

        public Criteria andDealerNameEqualTo(String value) {
            addCriterion("dealer_name =", value, "dealerName");
            return (Criteria) this;
        }

        public Criteria andDealerNameNotEqualTo(String value) {
            addCriterion("dealer_name <>", value, "dealerName");
            return (Criteria) this;
        }

        public Criteria andDealerNameGreaterThan(String value) {
            addCriterion("dealer_name >", value, "dealerName");
            return (Criteria) this;
        }

        public Criteria andDealerNameGreaterThanOrEqualTo(String value) {
            addCriterion("dealer_name >=", value, "dealerName");
            return (Criteria) this;
        }

        public Criteria andDealerNameLessThan(String value) {
            addCriterion("dealer_name <", value, "dealerName");
            return (Criteria) this;
        }

        public Criteria andDealerNameLessThanOrEqualTo(String value) {
            addCriterion("dealer_name <=", value, "dealerName");
            return (Criteria) this;
        }

        public Criteria andDealerNameLike(String value) {
            addCriterion("dealer_name like", value, "dealerName");
            return (Criteria) this;
        }

        public Criteria andDealerNameNotLike(String value) {
            addCriterion("dealer_name not like", value, "dealerName");
            return (Criteria) this;
        }

        public Criteria andDealerNameIn(List<String> values) {
            addCriterion("dealer_name in", values, "dealerName");
            return (Criteria) this;
        }

        public Criteria andDealerNameNotIn(List<String> values) {
            addCriterion("dealer_name not in", values, "dealerName");
            return (Criteria) this;
        }

        public Criteria andDealerNameBetween(String value1, String value2) {
            addCriterion("dealer_name between", value1, value2, "dealerName");
            return (Criteria) this;
        }

        public Criteria andDealerNameNotBetween(String value1, String value2) {
            addCriterion("dealer_name not between", value1, value2, "dealerName");
            return (Criteria) this;
        }

        public Criteria andIstotalIsNull() {
            addCriterion("isTotal is null");
            return (Criteria) this;
        }

        public Criteria andIstotalIsNotNull() {
            addCriterion("isTotal is not null");
            return (Criteria) this;
        }

        public Criteria andIstotalEqualTo(Integer value) {
            addCriterion("isTotal =", value, "istotal");
            return (Criteria) this;
        }

        public Criteria andIstotalNotEqualTo(Integer value) {
            addCriterion("isTotal <>", value, "istotal");
            return (Criteria) this;
        }

        public Criteria andIstotalGreaterThan(Integer value) {
            addCriterion("isTotal >", value, "istotal");
            return (Criteria) this;
        }

        public Criteria andIstotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("isTotal >=", value, "istotal");
            return (Criteria) this;
        }

        public Criteria andIstotalLessThan(Integer value) {
            addCriterion("isTotal <", value, "istotal");
            return (Criteria) this;
        }

        public Criteria andIstotalLessThanOrEqualTo(Integer value) {
            addCriterion("isTotal <=", value, "istotal");
            return (Criteria) this;
        }

        public Criteria andIstotalIn(List<Integer> values) {
            addCriterion("isTotal in", values, "istotal");
            return (Criteria) this;
        }

        public Criteria andIstotalNotIn(List<Integer> values) {
            addCriterion("isTotal not in", values, "istotal");
            return (Criteria) this;
        }

        public Criteria andIstotalBetween(Integer value1, Integer value2) {
            addCriterion("isTotal between", value1, value2, "istotal");
            return (Criteria) this;
        }

        public Criteria andIstotalNotBetween(Integer value1, Integer value2) {
            addCriterion("isTotal not between", value1, value2, "istotal");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table market_activity_report_week
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table market_activity_report_week
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}