package cn.lby.entity;

import java.util.ArrayList;
import java.util.List;

public class MarketActivityReportWeekClosingIntentionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table market_activity_report_week_closing_intention
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table market_activity_report_week_closing_intention
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table market_activity_report_week_closing_intention
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week_closing_intention
     *
     * @mbggenerated
     */
    public MarketActivityReportWeekClosingIntentionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week_closing_intention
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week_closing_intention
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week_closing_intention
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week_closing_intention
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week_closing_intention
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week_closing_intention
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week_closing_intention
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week_closing_intention
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week_closing_intention
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_activity_report_week_closing_intention
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table market_activity_report_week_closing_intention
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMarketActivityReportWeekIdIsNull() {
            addCriterion("market_activity_report_week_id is null");
            return (Criteria) this;
        }

        public Criteria andMarketActivityReportWeekIdIsNotNull() {
            addCriterion("market_activity_report_week_id is not null");
            return (Criteria) this;
        }

        public Criteria andMarketActivityReportWeekIdEqualTo(String value) {
            addCriterion("market_activity_report_week_id =", value, "marketActivityReportWeekId");
            return (Criteria) this;
        }

        public Criteria andMarketActivityReportWeekIdNotEqualTo(String value) {
            addCriterion("market_activity_report_week_id <>", value, "marketActivityReportWeekId");
            return (Criteria) this;
        }

        public Criteria andMarketActivityReportWeekIdGreaterThan(String value) {
            addCriterion("market_activity_report_week_id >", value, "marketActivityReportWeekId");
            return (Criteria) this;
        }

        public Criteria andMarketActivityReportWeekIdGreaterThanOrEqualTo(String value) {
            addCriterion("market_activity_report_week_id >=", value, "marketActivityReportWeekId");
            return (Criteria) this;
        }

        public Criteria andMarketActivityReportWeekIdLessThan(String value) {
            addCriterion("market_activity_report_week_id <", value, "marketActivityReportWeekId");
            return (Criteria) this;
        }

        public Criteria andMarketActivityReportWeekIdLessThanOrEqualTo(String value) {
            addCriterion("market_activity_report_week_id <=", value, "marketActivityReportWeekId");
            return (Criteria) this;
        }

        public Criteria andMarketActivityReportWeekIdLike(String value) {
            addCriterion("market_activity_report_week_id like", value, "marketActivityReportWeekId");
            return (Criteria) this;
        }

        public Criteria andMarketActivityReportWeekIdNotLike(String value) {
            addCriterion("market_activity_report_week_id not like", value, "marketActivityReportWeekId");
            return (Criteria) this;
        }

        public Criteria andMarketActivityReportWeekIdIn(List<String> values) {
            addCriterion("market_activity_report_week_id in", values, "marketActivityReportWeekId");
            return (Criteria) this;
        }

        public Criteria andMarketActivityReportWeekIdNotIn(List<String> values) {
            addCriterion("market_activity_report_week_id not in", values, "marketActivityReportWeekId");
            return (Criteria) this;
        }

        public Criteria andMarketActivityReportWeekIdBetween(String value1, String value2) {
            addCriterion("market_activity_report_week_id between", value1, value2, "marketActivityReportWeekId");
            return (Criteria) this;
        }

        public Criteria andMarketActivityReportWeekIdNotBetween(String value1, String value2) {
            addCriterion("market_activity_report_week_id not between", value1, value2, "marketActivityReportWeekId");
            return (Criteria) this;
        }

        public Criteria andLevelOfIntentIsNull() {
            addCriterion("level_of_intent is null");
            return (Criteria) this;
        }

        public Criteria andLevelOfIntentIsNotNull() {
            addCriterion("level_of_intent is not null");
            return (Criteria) this;
        }

        public Criteria andLevelOfIntentEqualTo(Integer value) {
            addCriterion("level_of_intent =", value, "levelOfIntent");
            return (Criteria) this;
        }

        public Criteria andLevelOfIntentNotEqualTo(Integer value) {
            addCriterion("level_of_intent <>", value, "levelOfIntent");
            return (Criteria) this;
        }

        public Criteria andLevelOfIntentGreaterThan(Integer value) {
            addCriterion("level_of_intent >", value, "levelOfIntent");
            return (Criteria) this;
        }

        public Criteria andLevelOfIntentGreaterThanOrEqualTo(Integer value) {
            addCriterion("level_of_intent >=", value, "levelOfIntent");
            return (Criteria) this;
        }

        public Criteria andLevelOfIntentLessThan(Integer value) {
            addCriterion("level_of_intent <", value, "levelOfIntent");
            return (Criteria) this;
        }

        public Criteria andLevelOfIntentLessThanOrEqualTo(Integer value) {
            addCriterion("level_of_intent <=", value, "levelOfIntent");
            return (Criteria) this;
        }

        public Criteria andLevelOfIntentIn(List<Integer> values) {
            addCriterion("level_of_intent in", values, "levelOfIntent");
            return (Criteria) this;
        }

        public Criteria andLevelOfIntentNotIn(List<Integer> values) {
            addCriterion("level_of_intent not in", values, "levelOfIntent");
            return (Criteria) this;
        }

        public Criteria andLevelOfIntentBetween(Integer value1, Integer value2) {
            addCriterion("level_of_intent between", value1, value2, "levelOfIntent");
            return (Criteria) this;
        }

        public Criteria andLevelOfIntentNotBetween(Integer value1, Integer value2) {
            addCriterion("level_of_intent not between", value1, value2, "levelOfIntent");
            return (Criteria) this;
        }

        public Criteria andClosingNumFristIsNull() {
            addCriterion("closing_num_frist is null");
            return (Criteria) this;
        }

        public Criteria andClosingNumFristIsNotNull() {
            addCriterion("closing_num_frist is not null");
            return (Criteria) this;
        }

        public Criteria andClosingNumFristEqualTo(Integer value) {
            addCriterion("closing_num_frist =", value, "closingNumFrist");
            return (Criteria) this;
        }

        public Criteria andClosingNumFristNotEqualTo(Integer value) {
            addCriterion("closing_num_frist <>", value, "closingNumFrist");
            return (Criteria) this;
        }

        public Criteria andClosingNumFristGreaterThan(Integer value) {
            addCriterion("closing_num_frist >", value, "closingNumFrist");
            return (Criteria) this;
        }

        public Criteria andClosingNumFristGreaterThanOrEqualTo(Integer value) {
            addCriterion("closing_num_frist >=", value, "closingNumFrist");
            return (Criteria) this;
        }

        public Criteria andClosingNumFristLessThan(Integer value) {
            addCriterion("closing_num_frist <", value, "closingNumFrist");
            return (Criteria) this;
        }

        public Criteria andClosingNumFristLessThanOrEqualTo(Integer value) {
            addCriterion("closing_num_frist <=", value, "closingNumFrist");
            return (Criteria) this;
        }

        public Criteria andClosingNumFristIn(List<Integer> values) {
            addCriterion("closing_num_frist in", values, "closingNumFrist");
            return (Criteria) this;
        }

        public Criteria andClosingNumFristNotIn(List<Integer> values) {
            addCriterion("closing_num_frist not in", values, "closingNumFrist");
            return (Criteria) this;
        }

        public Criteria andClosingNumFristBetween(Integer value1, Integer value2) {
            addCriterion("closing_num_frist between", value1, value2, "closingNumFrist");
            return (Criteria) this;
        }

        public Criteria andClosingNumFristNotBetween(Integer value1, Integer value2) {
            addCriterion("closing_num_frist not between", value1, value2, "closingNumFrist");
            return (Criteria) this;
        }

        public Criteria andNumFirstIsNull() {
            addCriterion("num_first is null");
            return (Criteria) this;
        }

        public Criteria andNumFirstIsNotNull() {
            addCriterion("num_first is not null");
            return (Criteria) this;
        }

        public Criteria andNumFirstEqualTo(Integer value) {
            addCriterion("num_first =", value, "numFirst");
            return (Criteria) this;
        }

        public Criteria andNumFirstNotEqualTo(Integer value) {
            addCriterion("num_first <>", value, "numFirst");
            return (Criteria) this;
        }

        public Criteria andNumFirstGreaterThan(Integer value) {
            addCriterion("num_first >", value, "numFirst");
            return (Criteria) this;
        }

        public Criteria andNumFirstGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_first >=", value, "numFirst");
            return (Criteria) this;
        }

        public Criteria andNumFirstLessThan(Integer value) {
            addCriterion("num_first <", value, "numFirst");
            return (Criteria) this;
        }

        public Criteria andNumFirstLessThanOrEqualTo(Integer value) {
            addCriterion("num_first <=", value, "numFirst");
            return (Criteria) this;
        }

        public Criteria andNumFirstIn(List<Integer> values) {
            addCriterion("num_first in", values, "numFirst");
            return (Criteria) this;
        }

        public Criteria andNumFirstNotIn(List<Integer> values) {
            addCriterion("num_first not in", values, "numFirst");
            return (Criteria) this;
        }

        public Criteria andNumFirstBetween(Integer value1, Integer value2) {
            addCriterion("num_first between", value1, value2, "numFirst");
            return (Criteria) this;
        }

        public Criteria andNumFirstNotBetween(Integer value1, Integer value2) {
            addCriterion("num_first not between", value1, value2, "numFirst");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table market_activity_report_week_closing_intention
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table market_activity_report_week_closing_intention
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}