package cn.lby.entity;

import java.util.Date;

public class RewardRecord {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reward_record.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reward_record.sales_record_id
	 * @mbggenerated
	 */
	private String salesRecordId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reward_record.customer_id
	 * @mbggenerated
	 */
	private String customerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reward_record.customer_name
	 * @mbggenerated
	 */
	private String customerName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reward_record.sale_consultant_id
	 * @mbggenerated
	 */
	private String saleConsultantId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reward_record.sale_consultant_name
	 * @mbggenerated
	 */
	private String saleConsultantName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reward_record.sale_consultant_mobile
	 * @mbggenerated
	 */
	private String saleConsultantMobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reward_record.status
	 * @mbggenerated
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reward_record.create_time
	 * @mbggenerated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reward_record.vehicle_model_id
	 * @mbggenerated
	 */
	private String vehicleModelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reward_record.vehicle_model_code
	 * @mbggenerated
	 */
	private String vehicleModelCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reward_record.vehicle_model_name
	 * @mbggenerated
	 */
	private String vehicleModelName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reward_record.score
	 * @mbggenerated
	 */
	private Integer score;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reward_record.market_activity_id
	 * @mbggenerated
	 */
	private String marketActivityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reward_record.market_activity_code
	 * @mbggenerated
	 */
	private String marketActivityCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reward_record.market_activity_name
	 * @mbggenerated
	 */
	private String marketActivityName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reward_record.reward_record_time
	 * @mbggenerated
	 */
	private Date rewardRecordTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reward_record.id
	 * @return  the value of reward_record.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reward_record.id
	 * @param id  the value for reward_record.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reward_record.sales_record_id
	 * @return  the value of reward_record.sales_record_id
	 * @mbggenerated
	 */
	public String getSalesRecordId() {
		return salesRecordId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reward_record.sales_record_id
	 * @param salesRecordId  the value for reward_record.sales_record_id
	 * @mbggenerated
	 */
	public void setSalesRecordId(String salesRecordId) {
		this.salesRecordId = salesRecordId == null ? null : salesRecordId
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reward_record.customer_id
	 * @return  the value of reward_record.customer_id
	 * @mbggenerated
	 */
	public String getCustomerId() {
		return customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reward_record.customer_id
	 * @param customerId  the value for reward_record.customer_id
	 * @mbggenerated
	 */
	public void setCustomerId(String customerId) {
		this.customerId = customerId == null ? null : customerId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reward_record.customer_name
	 * @return  the value of reward_record.customer_name
	 * @mbggenerated
	 */
	public String getCustomerName() {
		return customerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reward_record.customer_name
	 * @param customerName  the value for reward_record.customer_name
	 * @mbggenerated
	 */
	public void setCustomerName(String customerName) {
		this.customerName = customerName == null ? null : customerName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reward_record.sale_consultant_id
	 * @return  the value of reward_record.sale_consultant_id
	 * @mbggenerated
	 */
	public String getSaleConsultantId() {
		return saleConsultantId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reward_record.sale_consultant_id
	 * @param saleConsultantId  the value for reward_record.sale_consultant_id
	 * @mbggenerated
	 */
	public void setSaleConsultantId(String saleConsultantId) {
		this.saleConsultantId = saleConsultantId == null ? null
				: saleConsultantId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reward_record.sale_consultant_name
	 * @return  the value of reward_record.sale_consultant_name
	 * @mbggenerated
	 */
	public String getSaleConsultantName() {
		return saleConsultantName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reward_record.sale_consultant_name
	 * @param saleConsultantName  the value for reward_record.sale_consultant_name
	 * @mbggenerated
	 */
	public void setSaleConsultantName(String saleConsultantName) {
		this.saleConsultantName = saleConsultantName == null ? null
				: saleConsultantName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reward_record.sale_consultant_mobile
	 * @return  the value of reward_record.sale_consultant_mobile
	 * @mbggenerated
	 */
	public String getSaleConsultantMobile() {
		return saleConsultantMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reward_record.sale_consultant_mobile
	 * @param saleConsultantMobile  the value for reward_record.sale_consultant_mobile
	 * @mbggenerated
	 */
	public void setSaleConsultantMobile(String saleConsultantMobile) {
		this.saleConsultantMobile = saleConsultantMobile == null ? null
				: saleConsultantMobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reward_record.status
	 * @return  the value of reward_record.status
	 * @mbggenerated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reward_record.status
	 * @param status  the value for reward_record.status
	 * @mbggenerated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reward_record.create_time
	 * @return  the value of reward_record.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reward_record.create_time
	 * @param createTime  the value for reward_record.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reward_record.vehicle_model_id
	 * @return  the value of reward_record.vehicle_model_id
	 * @mbggenerated
	 */
	public String getVehicleModelId() {
		return vehicleModelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reward_record.vehicle_model_id
	 * @param vehicleModelId  the value for reward_record.vehicle_model_id
	 * @mbggenerated
	 */
	public void setVehicleModelId(String vehicleModelId) {
		this.vehicleModelId = vehicleModelId == null ? null : vehicleModelId
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reward_record.vehicle_model_code
	 * @return  the value of reward_record.vehicle_model_code
	 * @mbggenerated
	 */
	public String getVehicleModelCode() {
		return vehicleModelCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reward_record.vehicle_model_code
	 * @param vehicleModelCode  the value for reward_record.vehicle_model_code
	 * @mbggenerated
	 */
	public void setVehicleModelCode(String vehicleModelCode) {
		this.vehicleModelCode = vehicleModelCode == null ? null
				: vehicleModelCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reward_record.vehicle_model_name
	 * @return  the value of reward_record.vehicle_model_name
	 * @mbggenerated
	 */
	public String getVehicleModelName() {
		return vehicleModelName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reward_record.vehicle_model_name
	 * @param vehicleModelName  the value for reward_record.vehicle_model_name
	 * @mbggenerated
	 */
	public void setVehicleModelName(String vehicleModelName) {
		this.vehicleModelName = vehicleModelName == null ? null
				: vehicleModelName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reward_record.score
	 * @return  the value of reward_record.score
	 * @mbggenerated
	 */
	public Integer getScore() {
		return score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reward_record.score
	 * @param score  the value for reward_record.score
	 * @mbggenerated
	 */
	public void setScore(Integer score) {
		this.score = score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reward_record.market_activity_id
	 * @return  the value of reward_record.market_activity_id
	 * @mbggenerated
	 */
	public String getMarketActivityId() {
		return marketActivityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reward_record.market_activity_id
	 * @param marketActivityId  the value for reward_record.market_activity_id
	 * @mbggenerated
	 */
	public void setMarketActivityId(String marketActivityId) {
		this.marketActivityId = marketActivityId == null ? null
				: marketActivityId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reward_record.market_activity_code
	 * @return  the value of reward_record.market_activity_code
	 * @mbggenerated
	 */
	public String getMarketActivityCode() {
		return marketActivityCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reward_record.market_activity_code
	 * @param marketActivityCode  the value for reward_record.market_activity_code
	 * @mbggenerated
	 */
	public void setMarketActivityCode(String marketActivityCode) {
		this.marketActivityCode = marketActivityCode == null ? null
				: marketActivityCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reward_record.market_activity_name
	 * @return  the value of reward_record.market_activity_name
	 * @mbggenerated
	 */
	public String getMarketActivityName() {
		return marketActivityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reward_record.market_activity_name
	 * @param marketActivityName  the value for reward_record.market_activity_name
	 * @mbggenerated
	 */
	public void setMarketActivityName(String marketActivityName) {
		this.marketActivityName = marketActivityName == null ? null
				: marketActivityName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reward_record.reward_record_time
	 * @return  the value of reward_record.reward_record_time
	 * @mbggenerated
	 */
	public Date getRewardRecordTime() {
		return rewardRecordTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reward_record.reward_record_time
	 * @param rewardRecordTime  the value for reward_record.reward_record_time
	 * @mbggenerated
	 */
	public void setRewardRecordTime(Date rewardRecordTime) {
		this.rewardRecordTime = rewardRecordTime;
	}
}