package cn.lby.entity;

import java.math.BigDecimal;
import java.util.Date;

public class SalesRecord {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sales_record.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sales_record.code
	 * @mbggenerated
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sales_record.market_activity_id
	 * @mbggenerated
	 */
	private String marketActivityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sales_record.market_activity_code
	 * @mbggenerated
	 */
	private String marketActivityCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sales_record.market_activity_name
	 * @mbggenerated
	 */
	private String marketActivityName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sales_record.customer_id
	 * @mbggenerated
	 */
	private String customerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sales_record.customer_code
	 * @mbggenerated
	 */
	private String customerCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sales_record.customer_name
	 * @mbggenerated
	 */
	private String customerName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sales_record.customer_mobile
	 * @mbggenerated
	 */
	private String customerMobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sales_record.customer_email
	 * @mbggenerated
	 */
	private String customerEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sales_record.buy_date
	 * @mbggenerated
	 */
	private Date buyDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sales_record.vehicle_model_id
	 * @mbggenerated
	 */
	private String vehicleModelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sales_record.vehicle_model_code
	 * @mbggenerated
	 */
	private String vehicleModelCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sales_record.vehicle_model_name
	 * @mbggenerated
	 */
	private String vehicleModelName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sales_record.vin
	 * @mbggenerated
	 */
	private String vin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sales_record.color
	 * @mbggenerated
	 */
	private Integer color;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sales_record.dealer_id
	 * @mbggenerated
	 */
	private String dealerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sales_record.dealer_code
	 * @mbggenerated
	 */
	private String dealerCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sales_record.dealer_name
	 * @mbggenerated
	 */
	private String dealerName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sales_record.sale_consultant_id
	 * @mbggenerated
	 */
	private String saleConsultantId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sales_record.sale_consultant_code
	 * @mbggenerated
	 */
	private String saleConsultantCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sales_record.sale_consultant_name
	 * @mbggenerated
	 */
	private String saleConsultantName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sales_record.vehicle_price
	 * @mbggenerated
	 */
	private BigDecimal vehiclePrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sales_record.brand_id
	 * @mbggenerated
	 */
	private String brandId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sales_record.brand_name
	 * @mbggenerated
	 */
	private String brandName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sales_record.manufacturer_id
	 * @mbggenerated
	 */
	private String manufacturerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sales_record.create_time
	 * @mbggenerated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sales_record.status
	 * @mbggenerated
	 */
	private Integer status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sales_record.id
	 * @return  the value of sales_record.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sales_record.id
	 * @param id  the value for sales_record.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sales_record.code
	 * @return  the value of sales_record.code
	 * @mbggenerated
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sales_record.code
	 * @param code  the value for sales_record.code
	 * @mbggenerated
	 */
	public void setCode(String code) {
		this.code = code == null ? null : code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sales_record.market_activity_id
	 * @return  the value of sales_record.market_activity_id
	 * @mbggenerated
	 */
	public String getMarketActivityId() {
		return marketActivityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sales_record.market_activity_id
	 * @param marketActivityId  the value for sales_record.market_activity_id
	 * @mbggenerated
	 */
	public void setMarketActivityId(String marketActivityId) {
		this.marketActivityId = marketActivityId == null ? null
				: marketActivityId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sales_record.market_activity_code
	 * @return  the value of sales_record.market_activity_code
	 * @mbggenerated
	 */
	public String getMarketActivityCode() {
		return marketActivityCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sales_record.market_activity_code
	 * @param marketActivityCode  the value for sales_record.market_activity_code
	 * @mbggenerated
	 */
	public void setMarketActivityCode(String marketActivityCode) {
		this.marketActivityCode = marketActivityCode == null ? null
				: marketActivityCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sales_record.market_activity_name
	 * @return  the value of sales_record.market_activity_name
	 * @mbggenerated
	 */
	public String getMarketActivityName() {
		return marketActivityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sales_record.market_activity_name
	 * @param marketActivityName  the value for sales_record.market_activity_name
	 * @mbggenerated
	 */
	public void setMarketActivityName(String marketActivityName) {
		this.marketActivityName = marketActivityName == null ? null
				: marketActivityName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sales_record.customer_id
	 * @return  the value of sales_record.customer_id
	 * @mbggenerated
	 */
	public String getCustomerId() {
		return customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sales_record.customer_id
	 * @param customerId  the value for sales_record.customer_id
	 * @mbggenerated
	 */
	public void setCustomerId(String customerId) {
		this.customerId = customerId == null ? null : customerId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sales_record.customer_code
	 * @return  the value of sales_record.customer_code
	 * @mbggenerated
	 */
	public String getCustomerCode() {
		return customerCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sales_record.customer_code
	 * @param customerCode  the value for sales_record.customer_code
	 * @mbggenerated
	 */
	public void setCustomerCode(String customerCode) {
		this.customerCode = customerCode == null ? null : customerCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sales_record.customer_name
	 * @return  the value of sales_record.customer_name
	 * @mbggenerated
	 */
	public String getCustomerName() {
		return customerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sales_record.customer_name
	 * @param customerName  the value for sales_record.customer_name
	 * @mbggenerated
	 */
	public void setCustomerName(String customerName) {
		this.customerName = customerName == null ? null : customerName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sales_record.customer_mobile
	 * @return  the value of sales_record.customer_mobile
	 * @mbggenerated
	 */
	public String getCustomerMobile() {
		return customerMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sales_record.customer_mobile
	 * @param customerMobile  the value for sales_record.customer_mobile
	 * @mbggenerated
	 */
	public void setCustomerMobile(String customerMobile) {
		this.customerMobile = customerMobile == null ? null : customerMobile
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sales_record.customer_email
	 * @return  the value of sales_record.customer_email
	 * @mbggenerated
	 */
	public String getCustomerEmail() {
		return customerEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sales_record.customer_email
	 * @param customerEmail  the value for sales_record.customer_email
	 * @mbggenerated
	 */
	public void setCustomerEmail(String customerEmail) {
		this.customerEmail = customerEmail == null ? null : customerEmail
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sales_record.buy_date
	 * @return  the value of sales_record.buy_date
	 * @mbggenerated
	 */
	public Date getBuyDate() {
		return buyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sales_record.buy_date
	 * @param buyDate  the value for sales_record.buy_date
	 * @mbggenerated
	 */
	public void setBuyDate(Date buyDate) {
		this.buyDate = buyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sales_record.vehicle_model_id
	 * @return  the value of sales_record.vehicle_model_id
	 * @mbggenerated
	 */
	public String getVehicleModelId() {
		return vehicleModelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sales_record.vehicle_model_id
	 * @param vehicleModelId  the value for sales_record.vehicle_model_id
	 * @mbggenerated
	 */
	public void setVehicleModelId(String vehicleModelId) {
		this.vehicleModelId = vehicleModelId == null ? null : vehicleModelId
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sales_record.vehicle_model_code
	 * @return  the value of sales_record.vehicle_model_code
	 * @mbggenerated
	 */
	public String getVehicleModelCode() {
		return vehicleModelCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sales_record.vehicle_model_code
	 * @param vehicleModelCode  the value for sales_record.vehicle_model_code
	 * @mbggenerated
	 */
	public void setVehicleModelCode(String vehicleModelCode) {
		this.vehicleModelCode = vehicleModelCode == null ? null
				: vehicleModelCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sales_record.vehicle_model_name
	 * @return  the value of sales_record.vehicle_model_name
	 * @mbggenerated
	 */
	public String getVehicleModelName() {
		return vehicleModelName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sales_record.vehicle_model_name
	 * @param vehicleModelName  the value for sales_record.vehicle_model_name
	 * @mbggenerated
	 */
	public void setVehicleModelName(String vehicleModelName) {
		this.vehicleModelName = vehicleModelName == null ? null
				: vehicleModelName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sales_record.vin
	 * @return  the value of sales_record.vin
	 * @mbggenerated
	 */
	public String getVin() {
		return vin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sales_record.vin
	 * @param vin  the value for sales_record.vin
	 * @mbggenerated
	 */
	public void setVin(String vin) {
		this.vin = vin == null ? null : vin.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sales_record.color
	 * @return  the value of sales_record.color
	 * @mbggenerated
	 */
	public Integer getColor() {
		return color;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sales_record.color
	 * @param color  the value for sales_record.color
	 * @mbggenerated
	 */
	public void setColor(Integer color) {
		this.color = color;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sales_record.dealer_id
	 * @return  the value of sales_record.dealer_id
	 * @mbggenerated
	 */
	public String getDealerId() {
		return dealerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sales_record.dealer_id
	 * @param dealerId  the value for sales_record.dealer_id
	 * @mbggenerated
	 */
	public void setDealerId(String dealerId) {
		this.dealerId = dealerId == null ? null : dealerId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sales_record.dealer_code
	 * @return  the value of sales_record.dealer_code
	 * @mbggenerated
	 */
	public String getDealerCode() {
		return dealerCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sales_record.dealer_code
	 * @param dealerCode  the value for sales_record.dealer_code
	 * @mbggenerated
	 */
	public void setDealerCode(String dealerCode) {
		this.dealerCode = dealerCode == null ? null : dealerCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sales_record.dealer_name
	 * @return  the value of sales_record.dealer_name
	 * @mbggenerated
	 */
	public String getDealerName() {
		return dealerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sales_record.dealer_name
	 * @param dealerName  the value for sales_record.dealer_name
	 * @mbggenerated
	 */
	public void setDealerName(String dealerName) {
		this.dealerName = dealerName == null ? null : dealerName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sales_record.sale_consultant_id
	 * @return  the value of sales_record.sale_consultant_id
	 * @mbggenerated
	 */
	public String getSaleConsultantId() {
		return saleConsultantId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sales_record.sale_consultant_id
	 * @param saleConsultantId  the value for sales_record.sale_consultant_id
	 * @mbggenerated
	 */
	public void setSaleConsultantId(String saleConsultantId) {
		this.saleConsultantId = saleConsultantId == null ? null
				: saleConsultantId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sales_record.sale_consultant_code
	 * @return  the value of sales_record.sale_consultant_code
	 * @mbggenerated
	 */
	public String getSaleConsultantCode() {
		return saleConsultantCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sales_record.sale_consultant_code
	 * @param saleConsultantCode  the value for sales_record.sale_consultant_code
	 * @mbggenerated
	 */
	public void setSaleConsultantCode(String saleConsultantCode) {
		this.saleConsultantCode = saleConsultantCode == null ? null
				: saleConsultantCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sales_record.sale_consultant_name
	 * @return  the value of sales_record.sale_consultant_name
	 * @mbggenerated
	 */
	public String getSaleConsultantName() {
		return saleConsultantName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sales_record.sale_consultant_name
	 * @param saleConsultantName  the value for sales_record.sale_consultant_name
	 * @mbggenerated
	 */
	public void setSaleConsultantName(String saleConsultantName) {
		this.saleConsultantName = saleConsultantName == null ? null
				: saleConsultantName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sales_record.vehicle_price
	 * @return  the value of sales_record.vehicle_price
	 * @mbggenerated
	 */
	public BigDecimal getVehiclePrice() {
		return vehiclePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sales_record.vehicle_price
	 * @param vehiclePrice  the value for sales_record.vehicle_price
	 * @mbggenerated
	 */
	public void setVehiclePrice(BigDecimal vehiclePrice) {
		this.vehiclePrice = vehiclePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sales_record.brand_id
	 * @return  the value of sales_record.brand_id
	 * @mbggenerated
	 */
	public String getBrandId() {
		return brandId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sales_record.brand_id
	 * @param brandId  the value for sales_record.brand_id
	 * @mbggenerated
	 */
	public void setBrandId(String brandId) {
		this.brandId = brandId == null ? null : brandId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sales_record.brand_name
	 * @return  the value of sales_record.brand_name
	 * @mbggenerated
	 */
	public String getBrandName() {
		return brandName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sales_record.brand_name
	 * @param brandName  the value for sales_record.brand_name
	 * @mbggenerated
	 */
	public void setBrandName(String brandName) {
		this.brandName = brandName == null ? null : brandName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sales_record.manufacturer_id
	 * @return  the value of sales_record.manufacturer_id
	 * @mbggenerated
	 */
	public String getManufacturerId() {
		return manufacturerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sales_record.manufacturer_id
	 * @param manufacturerId  the value for sales_record.manufacturer_id
	 * @mbggenerated
	 */
	public void setManufacturerId(String manufacturerId) {
		this.manufacturerId = manufacturerId == null ? null : manufacturerId
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sales_record.create_time
	 * @return  the value of sales_record.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sales_record.create_time
	 * @param createTime  the value for sales_record.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sales_record.status
	 * @return  the value of sales_record.status
	 * @mbggenerated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sales_record.status
	 * @param status  the value for sales_record.status
	 * @mbggenerated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}
}