package cn.lby.entity;

import java.util.Date;

public class SalesRankingType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_ranking_type.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_ranking_type.time
     *
     * @mbggenerated
     */
    private String time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_ranking_type.dealer_id
     *
     * @mbggenerated
     */
    private String dealerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_ranking_type.dealer_code
     *
     * @mbggenerated
     */
    private String dealerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_ranking_type.dealer_name
     *
     * @mbggenerated
     */
    private String dealerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_ranking_type.vehicle_model_id
     *
     * @mbggenerated
     */
    private String vehicleModelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_ranking_type.vehicle_model_code
     *
     * @mbggenerated
     */
    private String vehicleModelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_ranking_type.vehicle_model_name
     *
     * @mbggenerated
     */
    private String vehicleModelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_ranking_type.market_activity_id
     *
     * @mbggenerated
     */
    private String marketActivityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_ranking_type.market_activity_code
     *
     * @mbggenerated
     */
    private String marketActivityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_ranking_type.market_activity_name
     *
     * @mbggenerated
     */
    private String marketActivityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_ranking_type.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_ranking_type.id
     *
     * @return the value of sales_ranking_type.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_ranking_type.id
     *
     * @param id the value for sales_ranking_type.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_ranking_type.time
     *
     * @return the value of sales_ranking_type.time
     *
     * @mbggenerated
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_ranking_type.time
     *
     * @param time the value for sales_ranking_type.time
     *
     * @mbggenerated
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_ranking_type.dealer_id
     *
     * @return the value of sales_ranking_type.dealer_id
     *
     * @mbggenerated
     */
    public String getDealerId() {
        return dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_ranking_type.dealer_id
     *
     * @param dealerId the value for sales_ranking_type.dealer_id
     *
     * @mbggenerated
     */
    public void setDealerId(String dealerId) {
        this.dealerId = dealerId == null ? null : dealerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_ranking_type.dealer_code
     *
     * @return the value of sales_ranking_type.dealer_code
     *
     * @mbggenerated
     */
    public String getDealerCode() {
        return dealerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_ranking_type.dealer_code
     *
     * @param dealerCode the value for sales_ranking_type.dealer_code
     *
     * @mbggenerated
     */
    public void setDealerCode(String dealerCode) {
        this.dealerCode = dealerCode == null ? null : dealerCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_ranking_type.dealer_name
     *
     * @return the value of sales_ranking_type.dealer_name
     *
     * @mbggenerated
     */
    public String getDealerName() {
        return dealerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_ranking_type.dealer_name
     *
     * @param dealerName the value for sales_ranking_type.dealer_name
     *
     * @mbggenerated
     */
    public void setDealerName(String dealerName) {
        this.dealerName = dealerName == null ? null : dealerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_ranking_type.vehicle_model_id
     *
     * @return the value of sales_ranking_type.vehicle_model_id
     *
     * @mbggenerated
     */
    public String getVehicleModelId() {
        return vehicleModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_ranking_type.vehicle_model_id
     *
     * @param vehicleModelId the value for sales_ranking_type.vehicle_model_id
     *
     * @mbggenerated
     */
    public void setVehicleModelId(String vehicleModelId) {
        this.vehicleModelId = vehicleModelId == null ? null : vehicleModelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_ranking_type.vehicle_model_code
     *
     * @return the value of sales_ranking_type.vehicle_model_code
     *
     * @mbggenerated
     */
    public String getVehicleModelCode() {
        return vehicleModelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_ranking_type.vehicle_model_code
     *
     * @param vehicleModelCode the value for sales_ranking_type.vehicle_model_code
     *
     * @mbggenerated
     */
    public void setVehicleModelCode(String vehicleModelCode) {
        this.vehicleModelCode = vehicleModelCode == null ? null : vehicleModelCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_ranking_type.vehicle_model_name
     *
     * @return the value of sales_ranking_type.vehicle_model_name
     *
     * @mbggenerated
     */
    public String getVehicleModelName() {
        return vehicleModelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_ranking_type.vehicle_model_name
     *
     * @param vehicleModelName the value for sales_ranking_type.vehicle_model_name
     *
     * @mbggenerated
     */
    public void setVehicleModelName(String vehicleModelName) {
        this.vehicleModelName = vehicleModelName == null ? null : vehicleModelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_ranking_type.market_activity_id
     *
     * @return the value of sales_ranking_type.market_activity_id
     *
     * @mbggenerated
     */
    public String getMarketActivityId() {
        return marketActivityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_ranking_type.market_activity_id
     *
     * @param marketActivityId the value for sales_ranking_type.market_activity_id
     *
     * @mbggenerated
     */
    public void setMarketActivityId(String marketActivityId) {
        this.marketActivityId = marketActivityId == null ? null : marketActivityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_ranking_type.market_activity_code
     *
     * @return the value of sales_ranking_type.market_activity_code
     *
     * @mbggenerated
     */
    public String getMarketActivityCode() {
        return marketActivityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_ranking_type.market_activity_code
     *
     * @param marketActivityCode the value for sales_ranking_type.market_activity_code
     *
     * @mbggenerated
     */
    public void setMarketActivityCode(String marketActivityCode) {
        this.marketActivityCode = marketActivityCode == null ? null : marketActivityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_ranking_type.market_activity_name
     *
     * @return the value of sales_ranking_type.market_activity_name
     *
     * @mbggenerated
     */
    public String getMarketActivityName() {
        return marketActivityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_ranking_type.market_activity_name
     *
     * @param marketActivityName the value for sales_ranking_type.market_activity_name
     *
     * @mbggenerated
     */
    public void setMarketActivityName(String marketActivityName) {
        this.marketActivityName = marketActivityName == null ? null : marketActivityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_ranking_type.create_time
     *
     * @return the value of sales_ranking_type.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_ranking_type.create_time
     *
     * @param createTime the value for sales_ranking_type.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}