package cn.lby.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SalesRecordExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sales_record
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sales_record
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sales_record
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sales_record
	 * @mbggenerated
	 */
	public SalesRecordExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sales_record
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sales_record
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sales_record
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sales_record
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sales_record
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sales_record
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sales_record
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sales_record
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sales_record
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sales_record
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sales_record
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andCodeIsNull() {
			addCriterion("code is null");
			return (Criteria) this;
		}

		public Criteria andCodeIsNotNull() {
			addCriterion("code is not null");
			return (Criteria) this;
		}

		public Criteria andCodeEqualTo(String value) {
			addCriterion("code =", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotEqualTo(String value) {
			addCriterion("code <>", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThan(String value) {
			addCriterion("code >", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThanOrEqualTo(String value) {
			addCriterion("code >=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThan(String value) {
			addCriterion("code <", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThanOrEqualTo(String value) {
			addCriterion("code <=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLike(String value) {
			addCriterion("code like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotLike(String value) {
			addCriterion("code not like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeIn(List<String> values) {
			addCriterion("code in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotIn(List<String> values) {
			addCriterion("code not in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeBetween(String value1, String value2) {
			addCriterion("code between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotBetween(String value1, String value2) {
			addCriterion("code not between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andMarketActivityIdIsNull() {
			addCriterion("market_activity_id is null");
			return (Criteria) this;
		}

		public Criteria andMarketActivityIdIsNotNull() {
			addCriterion("market_activity_id is not null");
			return (Criteria) this;
		}

		public Criteria andMarketActivityIdEqualTo(String value) {
			addCriterion("market_activity_id =", value, "marketActivityId");
			return (Criteria) this;
		}

		public Criteria andMarketActivityIdNotEqualTo(String value) {
			addCriterion("market_activity_id <>", value, "marketActivityId");
			return (Criteria) this;
		}

		public Criteria andMarketActivityIdGreaterThan(String value) {
			addCriterion("market_activity_id >", value, "marketActivityId");
			return (Criteria) this;
		}

		public Criteria andMarketActivityIdGreaterThanOrEqualTo(String value) {
			addCriterion("market_activity_id >=", value, "marketActivityId");
			return (Criteria) this;
		}

		public Criteria andMarketActivityIdLessThan(String value) {
			addCriterion("market_activity_id <", value, "marketActivityId");
			return (Criteria) this;
		}

		public Criteria andMarketActivityIdLessThanOrEqualTo(String value) {
			addCriterion("market_activity_id <=", value, "marketActivityId");
			return (Criteria) this;
		}

		public Criteria andMarketActivityIdLike(String value) {
			addCriterion("market_activity_id like", value, "marketActivityId");
			return (Criteria) this;
		}

		public Criteria andMarketActivityIdNotLike(String value) {
			addCriterion("market_activity_id not like", value,
					"marketActivityId");
			return (Criteria) this;
		}

		public Criteria andMarketActivityIdIn(List<String> values) {
			addCriterion("market_activity_id in", values, "marketActivityId");
			return (Criteria) this;
		}

		public Criteria andMarketActivityIdNotIn(List<String> values) {
			addCriterion("market_activity_id not in", values,
					"marketActivityId");
			return (Criteria) this;
		}

		public Criteria andMarketActivityIdBetween(String value1, String value2) {
			addCriterion("market_activity_id between", value1, value2,
					"marketActivityId");
			return (Criteria) this;
		}

		public Criteria andMarketActivityIdNotBetween(String value1,
				String value2) {
			addCriterion("market_activity_id not between", value1, value2,
					"marketActivityId");
			return (Criteria) this;
		}

		public Criteria andMarketActivityCodeIsNull() {
			addCriterion("market_activity_code is null");
			return (Criteria) this;
		}

		public Criteria andMarketActivityCodeIsNotNull() {
			addCriterion("market_activity_code is not null");
			return (Criteria) this;
		}

		public Criteria andMarketActivityCodeEqualTo(String value) {
			addCriterion("market_activity_code =", value, "marketActivityCode");
			return (Criteria) this;
		}

		public Criteria andMarketActivityCodeNotEqualTo(String value) {
			addCriterion("market_activity_code <>", value, "marketActivityCode");
			return (Criteria) this;
		}

		public Criteria andMarketActivityCodeGreaterThan(String value) {
			addCriterion("market_activity_code >", value, "marketActivityCode");
			return (Criteria) this;
		}

		public Criteria andMarketActivityCodeGreaterThanOrEqualTo(String value) {
			addCriterion("market_activity_code >=", value, "marketActivityCode");
			return (Criteria) this;
		}

		public Criteria andMarketActivityCodeLessThan(String value) {
			addCriterion("market_activity_code <", value, "marketActivityCode");
			return (Criteria) this;
		}

		public Criteria andMarketActivityCodeLessThanOrEqualTo(String value) {
			addCriterion("market_activity_code <=", value, "marketActivityCode");
			return (Criteria) this;
		}

		public Criteria andMarketActivityCodeLike(String value) {
			addCriterion("market_activity_code like", value,
					"marketActivityCode");
			return (Criteria) this;
		}

		public Criteria andMarketActivityCodeNotLike(String value) {
			addCriterion("market_activity_code not like", value,
					"marketActivityCode");
			return (Criteria) this;
		}

		public Criteria andMarketActivityCodeIn(List<String> values) {
			addCriterion("market_activity_code in", values,
					"marketActivityCode");
			return (Criteria) this;
		}

		public Criteria andMarketActivityCodeNotIn(List<String> values) {
			addCriterion("market_activity_code not in", values,
					"marketActivityCode");
			return (Criteria) this;
		}

		public Criteria andMarketActivityCodeBetween(String value1,
				String value2) {
			addCriterion("market_activity_code between", value1, value2,
					"marketActivityCode");
			return (Criteria) this;
		}

		public Criteria andMarketActivityCodeNotBetween(String value1,
				String value2) {
			addCriterion("market_activity_code not between", value1, value2,
					"marketActivityCode");
			return (Criteria) this;
		}

		public Criteria andMarketActivityNameIsNull() {
			addCriterion("market_activity_name is null");
			return (Criteria) this;
		}

		public Criteria andMarketActivityNameIsNotNull() {
			addCriterion("market_activity_name is not null");
			return (Criteria) this;
		}

		public Criteria andMarketActivityNameEqualTo(String value) {
			addCriterion("market_activity_name =", value, "marketActivityName");
			return (Criteria) this;
		}

		public Criteria andMarketActivityNameNotEqualTo(String value) {
			addCriterion("market_activity_name <>", value, "marketActivityName");
			return (Criteria) this;
		}

		public Criteria andMarketActivityNameGreaterThan(String value) {
			addCriterion("market_activity_name >", value, "marketActivityName");
			return (Criteria) this;
		}

		public Criteria andMarketActivityNameGreaterThanOrEqualTo(String value) {
			addCriterion("market_activity_name >=", value, "marketActivityName");
			return (Criteria) this;
		}

		public Criteria andMarketActivityNameLessThan(String value) {
			addCriterion("market_activity_name <", value, "marketActivityName");
			return (Criteria) this;
		}

		public Criteria andMarketActivityNameLessThanOrEqualTo(String value) {
			addCriterion("market_activity_name <=", value, "marketActivityName");
			return (Criteria) this;
		}

		public Criteria andMarketActivityNameLike(String value) {
			addCriterion("market_activity_name like", value,
					"marketActivityName");
			return (Criteria) this;
		}

		public Criteria andMarketActivityNameNotLike(String value) {
			addCriterion("market_activity_name not like", value,
					"marketActivityName");
			return (Criteria) this;
		}

		public Criteria andMarketActivityNameIn(List<String> values) {
			addCriterion("market_activity_name in", values,
					"marketActivityName");
			return (Criteria) this;
		}

		public Criteria andMarketActivityNameNotIn(List<String> values) {
			addCriterion("market_activity_name not in", values,
					"marketActivityName");
			return (Criteria) this;
		}

		public Criteria andMarketActivityNameBetween(String value1,
				String value2) {
			addCriterion("market_activity_name between", value1, value2,
					"marketActivityName");
			return (Criteria) this;
		}

		public Criteria andMarketActivityNameNotBetween(String value1,
				String value2) {
			addCriterion("market_activity_name not between", value1, value2,
					"marketActivityName");
			return (Criteria) this;
		}

		public Criteria andCustomerIdIsNull() {
			addCriterion("customer_id is null");
			return (Criteria) this;
		}

		public Criteria andCustomerIdIsNotNull() {
			addCriterion("customer_id is not null");
			return (Criteria) this;
		}

		public Criteria andCustomerIdEqualTo(String value) {
			addCriterion("customer_id =", value, "customerId");
			return (Criteria) this;
		}

		public Criteria andCustomerIdNotEqualTo(String value) {
			addCriterion("customer_id <>", value, "customerId");
			return (Criteria) this;
		}

		public Criteria andCustomerIdGreaterThan(String value) {
			addCriterion("customer_id >", value, "customerId");
			return (Criteria) this;
		}

		public Criteria andCustomerIdGreaterThanOrEqualTo(String value) {
			addCriterion("customer_id >=", value, "customerId");
			return (Criteria) this;
		}

		public Criteria andCustomerIdLessThan(String value) {
			addCriterion("customer_id <", value, "customerId");
			return (Criteria) this;
		}

		public Criteria andCustomerIdLessThanOrEqualTo(String value) {
			addCriterion("customer_id <=", value, "customerId");
			return (Criteria) this;
		}

		public Criteria andCustomerIdLike(String value) {
			addCriterion("customer_id like", value, "customerId");
			return (Criteria) this;
		}

		public Criteria andCustomerIdNotLike(String value) {
			addCriterion("customer_id not like", value, "customerId");
			return (Criteria) this;
		}

		public Criteria andCustomerIdIn(List<String> values) {
			addCriterion("customer_id in", values, "customerId");
			return (Criteria) this;
		}

		public Criteria andCustomerIdNotIn(List<String> values) {
			addCriterion("customer_id not in", values, "customerId");
			return (Criteria) this;
		}

		public Criteria andCustomerIdBetween(String value1, String value2) {
			addCriterion("customer_id between", value1, value2, "customerId");
			return (Criteria) this;
		}

		public Criteria andCustomerIdNotBetween(String value1, String value2) {
			addCriterion("customer_id not between", value1, value2,
					"customerId");
			return (Criteria) this;
		}

		public Criteria andCustomerCodeIsNull() {
			addCriterion("customer_code is null");
			return (Criteria) this;
		}

		public Criteria andCustomerCodeIsNotNull() {
			addCriterion("customer_code is not null");
			return (Criteria) this;
		}

		public Criteria andCustomerCodeEqualTo(String value) {
			addCriterion("customer_code =", value, "customerCode");
			return (Criteria) this;
		}

		public Criteria andCustomerCodeNotEqualTo(String value) {
			addCriterion("customer_code <>", value, "customerCode");
			return (Criteria) this;
		}

		public Criteria andCustomerCodeGreaterThan(String value) {
			addCriterion("customer_code >", value, "customerCode");
			return (Criteria) this;
		}

		public Criteria andCustomerCodeGreaterThanOrEqualTo(String value) {
			addCriterion("customer_code >=", value, "customerCode");
			return (Criteria) this;
		}

		public Criteria andCustomerCodeLessThan(String value) {
			addCriterion("customer_code <", value, "customerCode");
			return (Criteria) this;
		}

		public Criteria andCustomerCodeLessThanOrEqualTo(String value) {
			addCriterion("customer_code <=", value, "customerCode");
			return (Criteria) this;
		}

		public Criteria andCustomerCodeLike(String value) {
			addCriterion("customer_code like", value, "customerCode");
			return (Criteria) this;
		}

		public Criteria andCustomerCodeNotLike(String value) {
			addCriterion("customer_code not like", value, "customerCode");
			return (Criteria) this;
		}

		public Criteria andCustomerCodeIn(List<String> values) {
			addCriterion("customer_code in", values, "customerCode");
			return (Criteria) this;
		}

		public Criteria andCustomerCodeNotIn(List<String> values) {
			addCriterion("customer_code not in", values, "customerCode");
			return (Criteria) this;
		}

		public Criteria andCustomerCodeBetween(String value1, String value2) {
			addCriterion("customer_code between", value1, value2,
					"customerCode");
			return (Criteria) this;
		}

		public Criteria andCustomerCodeNotBetween(String value1, String value2) {
			addCriterion("customer_code not between", value1, value2,
					"customerCode");
			return (Criteria) this;
		}

		public Criteria andCustomerNameIsNull() {
			addCriterion("customer_name is null");
			return (Criteria) this;
		}

		public Criteria andCustomerNameIsNotNull() {
			addCriterion("customer_name is not null");
			return (Criteria) this;
		}

		public Criteria andCustomerNameEqualTo(String value) {
			addCriterion("customer_name =", value, "customerName");
			return (Criteria) this;
		}

		public Criteria andCustomerNameNotEqualTo(String value) {
			addCriterion("customer_name <>", value, "customerName");
			return (Criteria) this;
		}

		public Criteria andCustomerNameGreaterThan(String value) {
			addCriterion("customer_name >", value, "customerName");
			return (Criteria) this;
		}

		public Criteria andCustomerNameGreaterThanOrEqualTo(String value) {
			addCriterion("customer_name >=", value, "customerName");
			return (Criteria) this;
		}

		public Criteria andCustomerNameLessThan(String value) {
			addCriterion("customer_name <", value, "customerName");
			return (Criteria) this;
		}

		public Criteria andCustomerNameLessThanOrEqualTo(String value) {
			addCriterion("customer_name <=", value, "customerName");
			return (Criteria) this;
		}

		public Criteria andCustomerNameLike(String value) {
			addCriterion("customer_name like", value, "customerName");
			return (Criteria) this;
		}

		public Criteria andCustomerNameNotLike(String value) {
			addCriterion("customer_name not like", value, "customerName");
			return (Criteria) this;
		}

		public Criteria andCustomerNameIn(List<String> values) {
			addCriterion("customer_name in", values, "customerName");
			return (Criteria) this;
		}

		public Criteria andCustomerNameNotIn(List<String> values) {
			addCriterion("customer_name not in", values, "customerName");
			return (Criteria) this;
		}

		public Criteria andCustomerNameBetween(String value1, String value2) {
			addCriterion("customer_name between", value1, value2,
					"customerName");
			return (Criteria) this;
		}

		public Criteria andCustomerNameNotBetween(String value1, String value2) {
			addCriterion("customer_name not between", value1, value2,
					"customerName");
			return (Criteria) this;
		}

		public Criteria andCustomerMobileIsNull() {
			addCriterion("customer_mobile is null");
			return (Criteria) this;
		}

		public Criteria andCustomerMobileIsNotNull() {
			addCriterion("customer_mobile is not null");
			return (Criteria) this;
		}

		public Criteria andCustomerMobileEqualTo(String value) {
			addCriterion("customer_mobile =", value, "customerMobile");
			return (Criteria) this;
		}

		public Criteria andCustomerMobileNotEqualTo(String value) {
			addCriterion("customer_mobile <>", value, "customerMobile");
			return (Criteria) this;
		}

		public Criteria andCustomerMobileGreaterThan(String value) {
			addCriterion("customer_mobile >", value, "customerMobile");
			return (Criteria) this;
		}

		public Criteria andCustomerMobileGreaterThanOrEqualTo(String value) {
			addCriterion("customer_mobile >=", value, "customerMobile");
			return (Criteria) this;
		}

		public Criteria andCustomerMobileLessThan(String value) {
			addCriterion("customer_mobile <", value, "customerMobile");
			return (Criteria) this;
		}

		public Criteria andCustomerMobileLessThanOrEqualTo(String value) {
			addCriterion("customer_mobile <=", value, "customerMobile");
			return (Criteria) this;
		}

		public Criteria andCustomerMobileLike(String value) {
			addCriterion("customer_mobile like", value, "customerMobile");
			return (Criteria) this;
		}

		public Criteria andCustomerMobileNotLike(String value) {
			addCriterion("customer_mobile not like", value, "customerMobile");
			return (Criteria) this;
		}

		public Criteria andCustomerMobileIn(List<String> values) {
			addCriterion("customer_mobile in", values, "customerMobile");
			return (Criteria) this;
		}

		public Criteria andCustomerMobileNotIn(List<String> values) {
			addCriterion("customer_mobile not in", values, "customerMobile");
			return (Criteria) this;
		}

		public Criteria andCustomerMobileBetween(String value1, String value2) {
			addCriterion("customer_mobile between", value1, value2,
					"customerMobile");
			return (Criteria) this;
		}

		public Criteria andCustomerMobileNotBetween(String value1, String value2) {
			addCriterion("customer_mobile not between", value1, value2,
					"customerMobile");
			return (Criteria) this;
		}

		public Criteria andCustomerEmailIsNull() {
			addCriterion("customer_email is null");
			return (Criteria) this;
		}

		public Criteria andCustomerEmailIsNotNull() {
			addCriterion("customer_email is not null");
			return (Criteria) this;
		}

		public Criteria andCustomerEmailEqualTo(String value) {
			addCriterion("customer_email =", value, "customerEmail");
			return (Criteria) this;
		}

		public Criteria andCustomerEmailNotEqualTo(String value) {
			addCriterion("customer_email <>", value, "customerEmail");
			return (Criteria) this;
		}

		public Criteria andCustomerEmailGreaterThan(String value) {
			addCriterion("customer_email >", value, "customerEmail");
			return (Criteria) this;
		}

		public Criteria andCustomerEmailGreaterThanOrEqualTo(String value) {
			addCriterion("customer_email >=", value, "customerEmail");
			return (Criteria) this;
		}

		public Criteria andCustomerEmailLessThan(String value) {
			addCriterion("customer_email <", value, "customerEmail");
			return (Criteria) this;
		}

		public Criteria andCustomerEmailLessThanOrEqualTo(String value) {
			addCriterion("customer_email <=", value, "customerEmail");
			return (Criteria) this;
		}

		public Criteria andCustomerEmailLike(String value) {
			addCriterion("customer_email like", value, "customerEmail");
			return (Criteria) this;
		}

		public Criteria andCustomerEmailNotLike(String value) {
			addCriterion("customer_email not like", value, "customerEmail");
			return (Criteria) this;
		}

		public Criteria andCustomerEmailIn(List<String> values) {
			addCriterion("customer_email in", values, "customerEmail");
			return (Criteria) this;
		}

		public Criteria andCustomerEmailNotIn(List<String> values) {
			addCriterion("customer_email not in", values, "customerEmail");
			return (Criteria) this;
		}

		public Criteria andCustomerEmailBetween(String value1, String value2) {
			addCriterion("customer_email between", value1, value2,
					"customerEmail");
			return (Criteria) this;
		}

		public Criteria andCustomerEmailNotBetween(String value1, String value2) {
			addCriterion("customer_email not between", value1, value2,
					"customerEmail");
			return (Criteria) this;
		}

		public Criteria andBuyDateIsNull() {
			addCriterion("buy_date is null");
			return (Criteria) this;
		}

		public Criteria andBuyDateIsNotNull() {
			addCriterion("buy_date is not null");
			return (Criteria) this;
		}

		public Criteria andBuyDateEqualTo(Date value) {
			addCriterion("buy_date =", value, "buyDate");
			return (Criteria) this;
		}

		public Criteria andBuyDateNotEqualTo(Date value) {
			addCriterion("buy_date <>", value, "buyDate");
			return (Criteria) this;
		}

		public Criteria andBuyDateGreaterThan(Date value) {
			addCriterion("buy_date >", value, "buyDate");
			return (Criteria) this;
		}

		public Criteria andBuyDateGreaterThanOrEqualTo(Date value) {
			addCriterion("buy_date >=", value, "buyDate");
			return (Criteria) this;
		}

		public Criteria andBuyDateLessThan(Date value) {
			addCriterion("buy_date <", value, "buyDate");
			return (Criteria) this;
		}

		public Criteria andBuyDateLessThanOrEqualTo(Date value) {
			addCriterion("buy_date <=", value, "buyDate");
			return (Criteria) this;
		}

		public Criteria andBuyDateIn(List<Date> values) {
			addCriterion("buy_date in", values, "buyDate");
			return (Criteria) this;
		}

		public Criteria andBuyDateNotIn(List<Date> values) {
			addCriterion("buy_date not in", values, "buyDate");
			return (Criteria) this;
		}

		public Criteria andBuyDateBetween(Date value1, Date value2) {
			addCriterion("buy_date between", value1, value2, "buyDate");
			return (Criteria) this;
		}

		public Criteria andBuyDateNotBetween(Date value1, Date value2) {
			addCriterion("buy_date not between", value1, value2, "buyDate");
			return (Criteria) this;
		}

		public Criteria andVehicleModelIdIsNull() {
			addCriterion("vehicle_model_id is null");
			return (Criteria) this;
		}

		public Criteria andVehicleModelIdIsNotNull() {
			addCriterion("vehicle_model_id is not null");
			return (Criteria) this;
		}

		public Criteria andVehicleModelIdEqualTo(String value) {
			addCriterion("vehicle_model_id =", value, "vehicleModelId");
			return (Criteria) this;
		}

		public Criteria andVehicleModelIdNotEqualTo(String value) {
			addCriterion("vehicle_model_id <>", value, "vehicleModelId");
			return (Criteria) this;
		}

		public Criteria andVehicleModelIdGreaterThan(String value) {
			addCriterion("vehicle_model_id >", value, "vehicleModelId");
			return (Criteria) this;
		}

		public Criteria andVehicleModelIdGreaterThanOrEqualTo(String value) {
			addCriterion("vehicle_model_id >=", value, "vehicleModelId");
			return (Criteria) this;
		}

		public Criteria andVehicleModelIdLessThan(String value) {
			addCriterion("vehicle_model_id <", value, "vehicleModelId");
			return (Criteria) this;
		}

		public Criteria andVehicleModelIdLessThanOrEqualTo(String value) {
			addCriterion("vehicle_model_id <=", value, "vehicleModelId");
			return (Criteria) this;
		}

		public Criteria andVehicleModelIdLike(String value) {
			addCriterion("vehicle_model_id like", value, "vehicleModelId");
			return (Criteria) this;
		}

		public Criteria andVehicleModelIdNotLike(String value) {
			addCriterion("vehicle_model_id not like", value, "vehicleModelId");
			return (Criteria) this;
		}

		public Criteria andVehicleModelIdIn(List<String> values) {
			addCriterion("vehicle_model_id in", values, "vehicleModelId");
			return (Criteria) this;
		}

		public Criteria andVehicleModelIdNotIn(List<String> values) {
			addCriterion("vehicle_model_id not in", values, "vehicleModelId");
			return (Criteria) this;
		}

		public Criteria andVehicleModelIdBetween(String value1, String value2) {
			addCriterion("vehicle_model_id between", value1, value2,
					"vehicleModelId");
			return (Criteria) this;
		}

		public Criteria andVehicleModelIdNotBetween(String value1, String value2) {
			addCriterion("vehicle_model_id not between", value1, value2,
					"vehicleModelId");
			return (Criteria) this;
		}

		public Criteria andVehicleModelCodeIsNull() {
			addCriterion("vehicle_model_code is null");
			return (Criteria) this;
		}

		public Criteria andVehicleModelCodeIsNotNull() {
			addCriterion("vehicle_model_code is not null");
			return (Criteria) this;
		}

		public Criteria andVehicleModelCodeEqualTo(String value) {
			addCriterion("vehicle_model_code =", value, "vehicleModelCode");
			return (Criteria) this;
		}

		public Criteria andVehicleModelCodeNotEqualTo(String value) {
			addCriterion("vehicle_model_code <>", value, "vehicleModelCode");
			return (Criteria) this;
		}

		public Criteria andVehicleModelCodeGreaterThan(String value) {
			addCriterion("vehicle_model_code >", value, "vehicleModelCode");
			return (Criteria) this;
		}

		public Criteria andVehicleModelCodeGreaterThanOrEqualTo(String value) {
			addCriterion("vehicle_model_code >=", value, "vehicleModelCode");
			return (Criteria) this;
		}

		public Criteria andVehicleModelCodeLessThan(String value) {
			addCriterion("vehicle_model_code <", value, "vehicleModelCode");
			return (Criteria) this;
		}

		public Criteria andVehicleModelCodeLessThanOrEqualTo(String value) {
			addCriterion("vehicle_model_code <=", value, "vehicleModelCode");
			return (Criteria) this;
		}

		public Criteria andVehicleModelCodeLike(String value) {
			addCriterion("vehicle_model_code like", value, "vehicleModelCode");
			return (Criteria) this;
		}

		public Criteria andVehicleModelCodeNotLike(String value) {
			addCriterion("vehicle_model_code not like", value,
					"vehicleModelCode");
			return (Criteria) this;
		}

		public Criteria andVehicleModelCodeIn(List<String> values) {
			addCriterion("vehicle_model_code in", values, "vehicleModelCode");
			return (Criteria) this;
		}

		public Criteria andVehicleModelCodeNotIn(List<String> values) {
			addCriterion("vehicle_model_code not in", values,
					"vehicleModelCode");
			return (Criteria) this;
		}

		public Criteria andVehicleModelCodeBetween(String value1, String value2) {
			addCriterion("vehicle_model_code between", value1, value2,
					"vehicleModelCode");
			return (Criteria) this;
		}

		public Criteria andVehicleModelCodeNotBetween(String value1,
				String value2) {
			addCriterion("vehicle_model_code not between", value1, value2,
					"vehicleModelCode");
			return (Criteria) this;
		}

		public Criteria andVehicleModelNameIsNull() {
			addCriterion("vehicle_model_name is null");
			return (Criteria) this;
		}

		public Criteria andVehicleModelNameIsNotNull() {
			addCriterion("vehicle_model_name is not null");
			return (Criteria) this;
		}

		public Criteria andVehicleModelNameEqualTo(String value) {
			addCriterion("vehicle_model_name =", value, "vehicleModelName");
			return (Criteria) this;
		}

		public Criteria andVehicleModelNameNotEqualTo(String value) {
			addCriterion("vehicle_model_name <>", value, "vehicleModelName");
			return (Criteria) this;
		}

		public Criteria andVehicleModelNameGreaterThan(String value) {
			addCriterion("vehicle_model_name >", value, "vehicleModelName");
			return (Criteria) this;
		}

		public Criteria andVehicleModelNameGreaterThanOrEqualTo(String value) {
			addCriterion("vehicle_model_name >=", value, "vehicleModelName");
			return (Criteria) this;
		}

		public Criteria andVehicleModelNameLessThan(String value) {
			addCriterion("vehicle_model_name <", value, "vehicleModelName");
			return (Criteria) this;
		}

		public Criteria andVehicleModelNameLessThanOrEqualTo(String value) {
			addCriterion("vehicle_model_name <=", value, "vehicleModelName");
			return (Criteria) this;
		}

		public Criteria andVehicleModelNameLike(String value) {
			addCriterion("vehicle_model_name like", value, "vehicleModelName");
			return (Criteria) this;
		}

		public Criteria andVehicleModelNameNotLike(String value) {
			addCriterion("vehicle_model_name not like", value,
					"vehicleModelName");
			return (Criteria) this;
		}

		public Criteria andVehicleModelNameIn(List<String> values) {
			addCriterion("vehicle_model_name in", values, "vehicleModelName");
			return (Criteria) this;
		}

		public Criteria andVehicleModelNameNotIn(List<String> values) {
			addCriterion("vehicle_model_name not in", values,
					"vehicleModelName");
			return (Criteria) this;
		}

		public Criteria andVehicleModelNameBetween(String value1, String value2) {
			addCriterion("vehicle_model_name between", value1, value2,
					"vehicleModelName");
			return (Criteria) this;
		}

		public Criteria andVehicleModelNameNotBetween(String value1,
				String value2) {
			addCriterion("vehicle_model_name not between", value1, value2,
					"vehicleModelName");
			return (Criteria) this;
		}

		public Criteria andVinIsNull() {
			addCriterion("vin is null");
			return (Criteria) this;
		}

		public Criteria andVinIsNotNull() {
			addCriterion("vin is not null");
			return (Criteria) this;
		}

		public Criteria andVinEqualTo(String value) {
			addCriterion("vin =", value, "vin");
			return (Criteria) this;
		}

		public Criteria andVinNotEqualTo(String value) {
			addCriterion("vin <>", value, "vin");
			return (Criteria) this;
		}

		public Criteria andVinGreaterThan(String value) {
			addCriterion("vin >", value, "vin");
			return (Criteria) this;
		}

		public Criteria andVinGreaterThanOrEqualTo(String value) {
			addCriterion("vin >=", value, "vin");
			return (Criteria) this;
		}

		public Criteria andVinLessThan(String value) {
			addCriterion("vin <", value, "vin");
			return (Criteria) this;
		}

		public Criteria andVinLessThanOrEqualTo(String value) {
			addCriterion("vin <=", value, "vin");
			return (Criteria) this;
		}

		public Criteria andVinLike(String value) {
			addCriterion("vin like", value, "vin");
			return (Criteria) this;
		}

		public Criteria andVinNotLike(String value) {
			addCriterion("vin not like", value, "vin");
			return (Criteria) this;
		}

		public Criteria andVinIn(List<String> values) {
			addCriterion("vin in", values, "vin");
			return (Criteria) this;
		}

		public Criteria andVinNotIn(List<String> values) {
			addCriterion("vin not in", values, "vin");
			return (Criteria) this;
		}

		public Criteria andVinBetween(String value1, String value2) {
			addCriterion("vin between", value1, value2, "vin");
			return (Criteria) this;
		}

		public Criteria andVinNotBetween(String value1, String value2) {
			addCriterion("vin not between", value1, value2, "vin");
			return (Criteria) this;
		}

		public Criteria andColorIsNull() {
			addCriterion("color is null");
			return (Criteria) this;
		}

		public Criteria andColorIsNotNull() {
			addCriterion("color is not null");
			return (Criteria) this;
		}

		public Criteria andColorEqualTo(Integer value) {
			addCriterion("color =", value, "color");
			return (Criteria) this;
		}

		public Criteria andColorNotEqualTo(Integer value) {
			addCriterion("color <>", value, "color");
			return (Criteria) this;
		}

		public Criteria andColorGreaterThan(Integer value) {
			addCriterion("color >", value, "color");
			return (Criteria) this;
		}

		public Criteria andColorGreaterThanOrEqualTo(Integer value) {
			addCriterion("color >=", value, "color");
			return (Criteria) this;
		}

		public Criteria andColorLessThan(Integer value) {
			addCriterion("color <", value, "color");
			return (Criteria) this;
		}

		public Criteria andColorLessThanOrEqualTo(Integer value) {
			addCriterion("color <=", value, "color");
			return (Criteria) this;
		}

		public Criteria andColorIn(List<Integer> values) {
			addCriterion("color in", values, "color");
			return (Criteria) this;
		}

		public Criteria andColorNotIn(List<Integer> values) {
			addCriterion("color not in", values, "color");
			return (Criteria) this;
		}

		public Criteria andColorBetween(Integer value1, Integer value2) {
			addCriterion("color between", value1, value2, "color");
			return (Criteria) this;
		}

		public Criteria andColorNotBetween(Integer value1, Integer value2) {
			addCriterion("color not between", value1, value2, "color");
			return (Criteria) this;
		}

		public Criteria andDealerIdIsNull() {
			addCriterion("dealer_id is null");
			return (Criteria) this;
		}

		public Criteria andDealerIdIsNotNull() {
			addCriterion("dealer_id is not null");
			return (Criteria) this;
		}

		public Criteria andDealerIdEqualTo(String value) {
			addCriterion("dealer_id =", value, "dealerId");
			return (Criteria) this;
		}

		public Criteria andDealerIdNotEqualTo(String value) {
			addCriterion("dealer_id <>", value, "dealerId");
			return (Criteria) this;
		}

		public Criteria andDealerIdGreaterThan(String value) {
			addCriterion("dealer_id >", value, "dealerId");
			return (Criteria) this;
		}

		public Criteria andDealerIdGreaterThanOrEqualTo(String value) {
			addCriterion("dealer_id >=", value, "dealerId");
			return (Criteria) this;
		}

		public Criteria andDealerIdLessThan(String value) {
			addCriterion("dealer_id <", value, "dealerId");
			return (Criteria) this;
		}

		public Criteria andDealerIdLessThanOrEqualTo(String value) {
			addCriterion("dealer_id <=", value, "dealerId");
			return (Criteria) this;
		}

		public Criteria andDealerIdLike(String value) {
			addCriterion("dealer_id like", value, "dealerId");
			return (Criteria) this;
		}

		public Criteria andDealerIdNotLike(String value) {
			addCriterion("dealer_id not like", value, "dealerId");
			return (Criteria) this;
		}

		public Criteria andDealerIdIn(List<String> values) {
			addCriterion("dealer_id in", values, "dealerId");
			return (Criteria) this;
		}

		public Criteria andDealerIdNotIn(List<String> values) {
			addCriterion("dealer_id not in", values, "dealerId");
			return (Criteria) this;
		}

		public Criteria andDealerIdBetween(String value1, String value2) {
			addCriterion("dealer_id between", value1, value2, "dealerId");
			return (Criteria) this;
		}

		public Criteria andDealerIdNotBetween(String value1, String value2) {
			addCriterion("dealer_id not between", value1, value2, "dealerId");
			return (Criteria) this;
		}

		public Criteria andDealerCodeIsNull() {
			addCriterion("dealer_code is null");
			return (Criteria) this;
		}

		public Criteria andDealerCodeIsNotNull() {
			addCriterion("dealer_code is not null");
			return (Criteria) this;
		}

		public Criteria andDealerCodeEqualTo(String value) {
			addCriterion("dealer_code =", value, "dealerCode");
			return (Criteria) this;
		}

		public Criteria andDealerCodeNotEqualTo(String value) {
			addCriterion("dealer_code <>", value, "dealerCode");
			return (Criteria) this;
		}

		public Criteria andDealerCodeGreaterThan(String value) {
			addCriterion("dealer_code >", value, "dealerCode");
			return (Criteria) this;
		}

		public Criteria andDealerCodeGreaterThanOrEqualTo(String value) {
			addCriterion("dealer_code >=", value, "dealerCode");
			return (Criteria) this;
		}

		public Criteria andDealerCodeLessThan(String value) {
			addCriterion("dealer_code <", value, "dealerCode");
			return (Criteria) this;
		}

		public Criteria andDealerCodeLessThanOrEqualTo(String value) {
			addCriterion("dealer_code <=", value, "dealerCode");
			return (Criteria) this;
		}

		public Criteria andDealerCodeLike(String value) {
			addCriterion("dealer_code like", value, "dealerCode");
			return (Criteria) this;
		}

		public Criteria andDealerCodeNotLike(String value) {
			addCriterion("dealer_code not like", value, "dealerCode");
			return (Criteria) this;
		}

		public Criteria andDealerCodeIn(List<String> values) {
			addCriterion("dealer_code in", values, "dealerCode");
			return (Criteria) this;
		}

		public Criteria andDealerCodeNotIn(List<String> values) {
			addCriterion("dealer_code not in", values, "dealerCode");
			return (Criteria) this;
		}

		public Criteria andDealerCodeBetween(String value1, String value2) {
			addCriterion("dealer_code between", value1, value2, "dealerCode");
			return (Criteria) this;
		}

		public Criteria andDealerCodeNotBetween(String value1, String value2) {
			addCriterion("dealer_code not between", value1, value2,
					"dealerCode");
			return (Criteria) this;
		}

		public Criteria andDealerNameIsNull() {
			addCriterion("dealer_name is null");
			return (Criteria) this;
		}

		public Criteria andDealerNameIsNotNull() {
			addCriterion("dealer_name is not null");
			return (Criteria) this;
		}

		public Criteria andDealerNameEqualTo(String value) {
			addCriterion("dealer_name =", value, "dealerName");
			return (Criteria) this;
		}

		public Criteria andDealerNameNotEqualTo(String value) {
			addCriterion("dealer_name <>", value, "dealerName");
			return (Criteria) this;
		}

		public Criteria andDealerNameGreaterThan(String value) {
			addCriterion("dealer_name >", value, "dealerName");
			return (Criteria) this;
		}

		public Criteria andDealerNameGreaterThanOrEqualTo(String value) {
			addCriterion("dealer_name >=", value, "dealerName");
			return (Criteria) this;
		}

		public Criteria andDealerNameLessThan(String value) {
			addCriterion("dealer_name <", value, "dealerName");
			return (Criteria) this;
		}

		public Criteria andDealerNameLessThanOrEqualTo(String value) {
			addCriterion("dealer_name <=", value, "dealerName");
			return (Criteria) this;
		}

		public Criteria andDealerNameLike(String value) {
			addCriterion("dealer_name like", value, "dealerName");
			return (Criteria) this;
		}

		public Criteria andDealerNameNotLike(String value) {
			addCriterion("dealer_name not like", value, "dealerName");
			return (Criteria) this;
		}

		public Criteria andDealerNameIn(List<String> values) {
			addCriterion("dealer_name in", values, "dealerName");
			return (Criteria) this;
		}

		public Criteria andDealerNameNotIn(List<String> values) {
			addCriterion("dealer_name not in", values, "dealerName");
			return (Criteria) this;
		}

		public Criteria andDealerNameBetween(String value1, String value2) {
			addCriterion("dealer_name between", value1, value2, "dealerName");
			return (Criteria) this;
		}

		public Criteria andDealerNameNotBetween(String value1, String value2) {
			addCriterion("dealer_name not between", value1, value2,
					"dealerName");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantIdIsNull() {
			addCriterion("sale_consultant_id is null");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantIdIsNotNull() {
			addCriterion("sale_consultant_id is not null");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantIdEqualTo(String value) {
			addCriterion("sale_consultant_id =", value, "saleConsultantId");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantIdNotEqualTo(String value) {
			addCriterion("sale_consultant_id <>", value, "saleConsultantId");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantIdGreaterThan(String value) {
			addCriterion("sale_consultant_id >", value, "saleConsultantId");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantIdGreaterThanOrEqualTo(String value) {
			addCriterion("sale_consultant_id >=", value, "saleConsultantId");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantIdLessThan(String value) {
			addCriterion("sale_consultant_id <", value, "saleConsultantId");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantIdLessThanOrEqualTo(String value) {
			addCriterion("sale_consultant_id <=", value, "saleConsultantId");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantIdLike(String value) {
			addCriterion("sale_consultant_id like", value, "saleConsultantId");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantIdNotLike(String value) {
			addCriterion("sale_consultant_id not like", value,
					"saleConsultantId");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantIdIn(List<String> values) {
			addCriterion("sale_consultant_id in", values, "saleConsultantId");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantIdNotIn(List<String> values) {
			addCriterion("sale_consultant_id not in", values,
					"saleConsultantId");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantIdBetween(String value1, String value2) {
			addCriterion("sale_consultant_id between", value1, value2,
					"saleConsultantId");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantIdNotBetween(String value1,
				String value2) {
			addCriterion("sale_consultant_id not between", value1, value2,
					"saleConsultantId");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantCodeIsNull() {
			addCriterion("sale_consultant_code is null");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantCodeIsNotNull() {
			addCriterion("sale_consultant_code is not null");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantCodeEqualTo(String value) {
			addCriterion("sale_consultant_code =", value, "saleConsultantCode");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantCodeNotEqualTo(String value) {
			addCriterion("sale_consultant_code <>", value, "saleConsultantCode");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantCodeGreaterThan(String value) {
			addCriterion("sale_consultant_code >", value, "saleConsultantCode");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantCodeGreaterThanOrEqualTo(String value) {
			addCriterion("sale_consultant_code >=", value, "saleConsultantCode");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantCodeLessThan(String value) {
			addCriterion("sale_consultant_code <", value, "saleConsultantCode");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantCodeLessThanOrEqualTo(String value) {
			addCriterion("sale_consultant_code <=", value, "saleConsultantCode");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantCodeLike(String value) {
			addCriterion("sale_consultant_code like", value,
					"saleConsultantCode");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantCodeNotLike(String value) {
			addCriterion("sale_consultant_code not like", value,
					"saleConsultantCode");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantCodeIn(List<String> values) {
			addCriterion("sale_consultant_code in", values,
					"saleConsultantCode");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantCodeNotIn(List<String> values) {
			addCriterion("sale_consultant_code not in", values,
					"saleConsultantCode");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantCodeBetween(String value1,
				String value2) {
			addCriterion("sale_consultant_code between", value1, value2,
					"saleConsultantCode");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantCodeNotBetween(String value1,
				String value2) {
			addCriterion("sale_consultant_code not between", value1, value2,
					"saleConsultantCode");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantNameIsNull() {
			addCriterion("sale_consultant_name is null");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantNameIsNotNull() {
			addCriterion("sale_consultant_name is not null");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantNameEqualTo(String value) {
			addCriterion("sale_consultant_name =", value, "saleConsultantName");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantNameNotEqualTo(String value) {
			addCriterion("sale_consultant_name <>", value, "saleConsultantName");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantNameGreaterThan(String value) {
			addCriterion("sale_consultant_name >", value, "saleConsultantName");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantNameGreaterThanOrEqualTo(String value) {
			addCriterion("sale_consultant_name >=", value, "saleConsultantName");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantNameLessThan(String value) {
			addCriterion("sale_consultant_name <", value, "saleConsultantName");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantNameLessThanOrEqualTo(String value) {
			addCriterion("sale_consultant_name <=", value, "saleConsultantName");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantNameLike(String value) {
			addCriterion("sale_consultant_name like", value,
					"saleConsultantName");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantNameNotLike(String value) {
			addCriterion("sale_consultant_name not like", value,
					"saleConsultantName");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantNameIn(List<String> values) {
			addCriterion("sale_consultant_name in", values,
					"saleConsultantName");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantNameNotIn(List<String> values) {
			addCriterion("sale_consultant_name not in", values,
					"saleConsultantName");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantNameBetween(String value1,
				String value2) {
			addCriterion("sale_consultant_name between", value1, value2,
					"saleConsultantName");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantNameNotBetween(String value1,
				String value2) {
			addCriterion("sale_consultant_name not between", value1, value2,
					"saleConsultantName");
			return (Criteria) this;
		}

		public Criteria andVehiclePriceIsNull() {
			addCriterion("vehicle_price is null");
			return (Criteria) this;
		}

		public Criteria andVehiclePriceIsNotNull() {
			addCriterion("vehicle_price is not null");
			return (Criteria) this;
		}

		public Criteria andVehiclePriceEqualTo(BigDecimal value) {
			addCriterion("vehicle_price =", value, "vehiclePrice");
			return (Criteria) this;
		}

		public Criteria andVehiclePriceNotEqualTo(BigDecimal value) {
			addCriterion("vehicle_price <>", value, "vehiclePrice");
			return (Criteria) this;
		}

		public Criteria andVehiclePriceGreaterThan(BigDecimal value) {
			addCriterion("vehicle_price >", value, "vehiclePrice");
			return (Criteria) this;
		}

		public Criteria andVehiclePriceGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("vehicle_price >=", value, "vehiclePrice");
			return (Criteria) this;
		}

		public Criteria andVehiclePriceLessThan(BigDecimal value) {
			addCriterion("vehicle_price <", value, "vehiclePrice");
			return (Criteria) this;
		}

		public Criteria andVehiclePriceLessThanOrEqualTo(BigDecimal value) {
			addCriterion("vehicle_price <=", value, "vehiclePrice");
			return (Criteria) this;
		}

		public Criteria andVehiclePriceIn(List<BigDecimal> values) {
			addCriterion("vehicle_price in", values, "vehiclePrice");
			return (Criteria) this;
		}

		public Criteria andVehiclePriceNotIn(List<BigDecimal> values) {
			addCriterion("vehicle_price not in", values, "vehiclePrice");
			return (Criteria) this;
		}

		public Criteria andVehiclePriceBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("vehicle_price between", value1, value2,
					"vehiclePrice");
			return (Criteria) this;
		}

		public Criteria andVehiclePriceNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("vehicle_price not between", value1, value2,
					"vehiclePrice");
			return (Criteria) this;
		}

		public Criteria andBrandIdIsNull() {
			addCriterion("brand_id is null");
			return (Criteria) this;
		}

		public Criteria andBrandIdIsNotNull() {
			addCriterion("brand_id is not null");
			return (Criteria) this;
		}

		public Criteria andBrandIdEqualTo(String value) {
			addCriterion("brand_id =", value, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdNotEqualTo(String value) {
			addCriterion("brand_id <>", value, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdGreaterThan(String value) {
			addCriterion("brand_id >", value, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdGreaterThanOrEqualTo(String value) {
			addCriterion("brand_id >=", value, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdLessThan(String value) {
			addCriterion("brand_id <", value, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdLessThanOrEqualTo(String value) {
			addCriterion("brand_id <=", value, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdLike(String value) {
			addCriterion("brand_id like", value, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdNotLike(String value) {
			addCriterion("brand_id not like", value, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdIn(List<String> values) {
			addCriterion("brand_id in", values, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdNotIn(List<String> values) {
			addCriterion("brand_id not in", values, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdBetween(String value1, String value2) {
			addCriterion("brand_id between", value1, value2, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdNotBetween(String value1, String value2) {
			addCriterion("brand_id not between", value1, value2, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandNameIsNull() {
			addCriterion("brand_name is null");
			return (Criteria) this;
		}

		public Criteria andBrandNameIsNotNull() {
			addCriterion("brand_name is not null");
			return (Criteria) this;
		}

		public Criteria andBrandNameEqualTo(String value) {
			addCriterion("brand_name =", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameNotEqualTo(String value) {
			addCriterion("brand_name <>", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameGreaterThan(String value) {
			addCriterion("brand_name >", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameGreaterThanOrEqualTo(String value) {
			addCriterion("brand_name >=", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameLessThan(String value) {
			addCriterion("brand_name <", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameLessThanOrEqualTo(String value) {
			addCriterion("brand_name <=", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameLike(String value) {
			addCriterion("brand_name like", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameNotLike(String value) {
			addCriterion("brand_name not like", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameIn(List<String> values) {
			addCriterion("brand_name in", values, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameNotIn(List<String> values) {
			addCriterion("brand_name not in", values, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameBetween(String value1, String value2) {
			addCriterion("brand_name between", value1, value2, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameNotBetween(String value1, String value2) {
			addCriterion("brand_name not between", value1, value2, "brandName");
			return (Criteria) this;
		}

		public Criteria andManufacturerIdIsNull() {
			addCriterion("manufacturer_id is null");
			return (Criteria) this;
		}

		public Criteria andManufacturerIdIsNotNull() {
			addCriterion("manufacturer_id is not null");
			return (Criteria) this;
		}

		public Criteria andManufacturerIdEqualTo(String value) {
			addCriterion("manufacturer_id =", value, "manufacturerId");
			return (Criteria) this;
		}

		public Criteria andManufacturerIdNotEqualTo(String value) {
			addCriterion("manufacturer_id <>", value, "manufacturerId");
			return (Criteria) this;
		}

		public Criteria andManufacturerIdGreaterThan(String value) {
			addCriterion("manufacturer_id >", value, "manufacturerId");
			return (Criteria) this;
		}

		public Criteria andManufacturerIdGreaterThanOrEqualTo(String value) {
			addCriterion("manufacturer_id >=", value, "manufacturerId");
			return (Criteria) this;
		}

		public Criteria andManufacturerIdLessThan(String value) {
			addCriterion("manufacturer_id <", value, "manufacturerId");
			return (Criteria) this;
		}

		public Criteria andManufacturerIdLessThanOrEqualTo(String value) {
			addCriterion("manufacturer_id <=", value, "manufacturerId");
			return (Criteria) this;
		}

		public Criteria andManufacturerIdLike(String value) {
			addCriterion("manufacturer_id like", value, "manufacturerId");
			return (Criteria) this;
		}

		public Criteria andManufacturerIdNotLike(String value) {
			addCriterion("manufacturer_id not like", value, "manufacturerId");
			return (Criteria) this;
		}

		public Criteria andManufacturerIdIn(List<String> values) {
			addCriterion("manufacturer_id in", values, "manufacturerId");
			return (Criteria) this;
		}

		public Criteria andManufacturerIdNotIn(List<String> values) {
			addCriterion("manufacturer_id not in", values, "manufacturerId");
			return (Criteria) this;
		}

		public Criteria andManufacturerIdBetween(String value1, String value2) {
			addCriterion("manufacturer_id between", value1, value2,
					"manufacturerId");
			return (Criteria) this;
		}

		public Criteria andManufacturerIdNotBetween(String value1, String value2) {
			addCriterion("manufacturer_id not between", value1, value2,
					"manufacturerId");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2,
					"createTime");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sales_record
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sales_record
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}