package cn.lby.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SalesRankingQaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sales_ranking_qa
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sales_ranking_qa
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sales_ranking_qa
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_ranking_qa
     *
     * @mbggenerated
     */
    public SalesRankingQaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_ranking_qa
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_ranking_qa
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_ranking_qa
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_ranking_qa
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_ranking_qa
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_ranking_qa
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_ranking_qa
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_ranking_qa
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_ranking_qa
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_ranking_qa
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sales_ranking_qa
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andRankingTypeIdIsNull() {
            addCriterion("ranking_type_id is null");
            return (Criteria) this;
        }

        public Criteria andRankingTypeIdIsNotNull() {
            addCriterion("ranking_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andRankingTypeIdEqualTo(String value) {
            addCriterion("ranking_type_id =", value, "rankingTypeId");
            return (Criteria) this;
        }

        public Criteria andRankingTypeIdNotEqualTo(String value) {
            addCriterion("ranking_type_id <>", value, "rankingTypeId");
            return (Criteria) this;
        }

        public Criteria andRankingTypeIdGreaterThan(String value) {
            addCriterion("ranking_type_id >", value, "rankingTypeId");
            return (Criteria) this;
        }

        public Criteria andRankingTypeIdGreaterThanOrEqualTo(String value) {
            addCriterion("ranking_type_id >=", value, "rankingTypeId");
            return (Criteria) this;
        }

        public Criteria andRankingTypeIdLessThan(String value) {
            addCriterion("ranking_type_id <", value, "rankingTypeId");
            return (Criteria) this;
        }

        public Criteria andRankingTypeIdLessThanOrEqualTo(String value) {
            addCriterion("ranking_type_id <=", value, "rankingTypeId");
            return (Criteria) this;
        }

        public Criteria andRankingTypeIdLike(String value) {
            addCriterion("ranking_type_id like", value, "rankingTypeId");
            return (Criteria) this;
        }

        public Criteria andRankingTypeIdNotLike(String value) {
            addCriterion("ranking_type_id not like", value, "rankingTypeId");
            return (Criteria) this;
        }

        public Criteria andRankingTypeIdIn(List<String> values) {
            addCriterion("ranking_type_id in", values, "rankingTypeId");
            return (Criteria) this;
        }

        public Criteria andRankingTypeIdNotIn(List<String> values) {
            addCriterion("ranking_type_id not in", values, "rankingTypeId");
            return (Criteria) this;
        }

        public Criteria andRankingTypeIdBetween(String value1, String value2) {
            addCriterion("ranking_type_id between", value1, value2, "rankingTypeId");
            return (Criteria) this;
        }

        public Criteria andRankingTypeIdNotBetween(String value1, String value2) {
            addCriterion("ranking_type_id not between", value1, value2, "rankingTypeId");
            return (Criteria) this;
        }

        public Criteria andSaleConsultantIdIsNull() {
            addCriterion("sale_consultant_id is null");
            return (Criteria) this;
        }

        public Criteria andSaleConsultantIdIsNotNull() {
            addCriterion("sale_consultant_id is not null");
            return (Criteria) this;
        }

        public Criteria andSaleConsultantIdEqualTo(String value) {
            addCriterion("sale_consultant_id =", value, "saleConsultantId");
            return (Criteria) this;
        }

        public Criteria andSaleConsultantIdNotEqualTo(String value) {
            addCriterion("sale_consultant_id <>", value, "saleConsultantId");
            return (Criteria) this;
        }

        public Criteria andSaleConsultantIdGreaterThan(String value) {
            addCriterion("sale_consultant_id >", value, "saleConsultantId");
            return (Criteria) this;
        }

        public Criteria andSaleConsultantIdGreaterThanOrEqualTo(String value) {
            addCriterion("sale_consultant_id >=", value, "saleConsultantId");
            return (Criteria) this;
        }

        public Criteria andSaleConsultantIdLessThan(String value) {
            addCriterion("sale_consultant_id <", value, "saleConsultantId");
            return (Criteria) this;
        }

        public Criteria andSaleConsultantIdLessThanOrEqualTo(String value) {
            addCriterion("sale_consultant_id <=", value, "saleConsultantId");
            return (Criteria) this;
        }

        public Criteria andSaleConsultantIdLike(String value) {
            addCriterion("sale_consultant_id like", value, "saleConsultantId");
            return (Criteria) this;
        }

        public Criteria andSaleConsultantIdNotLike(String value) {
            addCriterion("sale_consultant_id not like", value, "saleConsultantId");
            return (Criteria) this;
        }

        public Criteria andSaleConsultantIdIn(List<String> values) {
            addCriterion("sale_consultant_id in", values, "saleConsultantId");
            return (Criteria) this;
        }

        public Criteria andSaleConsultantIdNotIn(List<String> values) {
            addCriterion("sale_consultant_id not in", values, "saleConsultantId");
            return (Criteria) this;
        }

        public Criteria andSaleConsultantIdBetween(String value1, String value2) {
            addCriterion("sale_consultant_id between", value1, value2, "saleConsultantId");
            return (Criteria) this;
        }

        public Criteria andSaleConsultantIdNotBetween(String value1, String value2) {
            addCriterion("sale_consultant_id not between", value1, value2, "saleConsultantId");
            return (Criteria) this;
        }

        public Criteria andSaleConsultantNameIsNull() {
            addCriterion("sale_consultant_name is null");
            return (Criteria) this;
        }

        public Criteria andSaleConsultantNameIsNotNull() {
            addCriterion("sale_consultant_name is not null");
            return (Criteria) this;
        }

        public Criteria andSaleConsultantNameEqualTo(String value) {
            addCriterion("sale_consultant_name =", value, "saleConsultantName");
            return (Criteria) this;
        }

        public Criteria andSaleConsultantNameNotEqualTo(String value) {
            addCriterion("sale_consultant_name <>", value, "saleConsultantName");
            return (Criteria) this;
        }

        public Criteria andSaleConsultantNameGreaterThan(String value) {
            addCriterion("sale_consultant_name >", value, "saleConsultantName");
            return (Criteria) this;
        }

        public Criteria andSaleConsultantNameGreaterThanOrEqualTo(String value) {
            addCriterion("sale_consultant_name >=", value, "saleConsultantName");
            return (Criteria) this;
        }

        public Criteria andSaleConsultantNameLessThan(String value) {
            addCriterion("sale_consultant_name <", value, "saleConsultantName");
            return (Criteria) this;
        }

        public Criteria andSaleConsultantNameLessThanOrEqualTo(String value) {
            addCriterion("sale_consultant_name <=", value, "saleConsultantName");
            return (Criteria) this;
        }

        public Criteria andSaleConsultantNameLike(String value) {
            addCriterion("sale_consultant_name like", value, "saleConsultantName");
            return (Criteria) this;
        }

        public Criteria andSaleConsultantNameNotLike(String value) {
            addCriterion("sale_consultant_name not like", value, "saleConsultantName");
            return (Criteria) this;
        }

        public Criteria andSaleConsultantNameIn(List<String> values) {
            addCriterion("sale_consultant_name in", values, "saleConsultantName");
            return (Criteria) this;
        }

        public Criteria andSaleConsultantNameNotIn(List<String> values) {
            addCriterion("sale_consultant_name not in", values, "saleConsultantName");
            return (Criteria) this;
        }

        public Criteria andSaleConsultantNameBetween(String value1, String value2) {
            addCriterion("sale_consultant_name between", value1, value2, "saleConsultantName");
            return (Criteria) this;
        }

        public Criteria andSaleConsultantNameNotBetween(String value1, String value2) {
            addCriterion("sale_consultant_name not between", value1, value2, "saleConsultantName");
            return (Criteria) this;
        }

        public Criteria andSalesVolumeIsNull() {
            addCriterion("sales_volume is null");
            return (Criteria) this;
        }

        public Criteria andSalesVolumeIsNotNull() {
            addCriterion("sales_volume is not null");
            return (Criteria) this;
        }

        public Criteria andSalesVolumeEqualTo(Integer value) {
            addCriterion("sales_volume =", value, "salesVolume");
            return (Criteria) this;
        }

        public Criteria andSalesVolumeNotEqualTo(Integer value) {
            addCriterion("sales_volume <>", value, "salesVolume");
            return (Criteria) this;
        }

        public Criteria andSalesVolumeGreaterThan(Integer value) {
            addCriterion("sales_volume >", value, "salesVolume");
            return (Criteria) this;
        }

        public Criteria andSalesVolumeGreaterThanOrEqualTo(Integer value) {
            addCriterion("sales_volume >=", value, "salesVolume");
            return (Criteria) this;
        }

        public Criteria andSalesVolumeLessThan(Integer value) {
            addCriterion("sales_volume <", value, "salesVolume");
            return (Criteria) this;
        }

        public Criteria andSalesVolumeLessThanOrEqualTo(Integer value) {
            addCriterion("sales_volume <=", value, "salesVolume");
            return (Criteria) this;
        }

        public Criteria andSalesVolumeIn(List<Integer> values) {
            addCriterion("sales_volume in", values, "salesVolume");
            return (Criteria) this;
        }

        public Criteria andSalesVolumeNotIn(List<Integer> values) {
            addCriterion("sales_volume not in", values, "salesVolume");
            return (Criteria) this;
        }

        public Criteria andSalesVolumeBetween(Integer value1, Integer value2) {
            addCriterion("sales_volume between", value1, value2, "salesVolume");
            return (Criteria) this;
        }

        public Criteria andSalesVolumeNotBetween(Integer value1, Integer value2) {
            addCriterion("sales_volume not between", value1, value2, "salesVolume");
            return (Criteria) this;
        }

        public Criteria andSatisfactionDegreeIsNull() {
            addCriterion("satisfaction_degree is null");
            return (Criteria) this;
        }

        public Criteria andSatisfactionDegreeIsNotNull() {
            addCriterion("satisfaction_degree is not null");
            return (Criteria) this;
        }

        public Criteria andSatisfactionDegreeEqualTo(Integer value) {
            addCriterion("satisfaction_degree =", value, "satisfactionDegree");
            return (Criteria) this;
        }

        public Criteria andSatisfactionDegreeNotEqualTo(Integer value) {
            addCriterion("satisfaction_degree <>", value, "satisfactionDegree");
            return (Criteria) this;
        }

        public Criteria andSatisfactionDegreeGreaterThan(Integer value) {
            addCriterion("satisfaction_degree >", value, "satisfactionDegree");
            return (Criteria) this;
        }

        public Criteria andSatisfactionDegreeGreaterThanOrEqualTo(Integer value) {
            addCriterion("satisfaction_degree >=", value, "satisfactionDegree");
            return (Criteria) this;
        }

        public Criteria andSatisfactionDegreeLessThan(Integer value) {
            addCriterion("satisfaction_degree <", value, "satisfactionDegree");
            return (Criteria) this;
        }

        public Criteria andSatisfactionDegreeLessThanOrEqualTo(Integer value) {
            addCriterion("satisfaction_degree <=", value, "satisfactionDegree");
            return (Criteria) this;
        }

        public Criteria andSatisfactionDegreeIn(List<Integer> values) {
            addCriterion("satisfaction_degree in", values, "satisfactionDegree");
            return (Criteria) this;
        }

        public Criteria andSatisfactionDegreeNotIn(List<Integer> values) {
            addCriterion("satisfaction_degree not in", values, "satisfactionDegree");
            return (Criteria) this;
        }

        public Criteria andSatisfactionDegreeBetween(Integer value1, Integer value2) {
            addCriterion("satisfaction_degree between", value1, value2, "satisfactionDegree");
            return (Criteria) this;
        }

        public Criteria andSatisfactionDegreeNotBetween(Integer value1, Integer value2) {
            addCriterion("satisfaction_degree not between", value1, value2, "satisfactionDegree");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sales_ranking_qa
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sales_ranking_qa
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}