package cn.lby.entity;

import java.util.Date;

public class SalesRankingQa {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_ranking_qa.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_ranking_qa.ranking_type_id
     *
     * @mbggenerated
     */
    private String rankingTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_ranking_qa.sale_consultant_id
     *
     * @mbggenerated
     */
    private String saleConsultantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_ranking_qa.sale_consultant_name
     *
     * @mbggenerated
     */
    private String saleConsultantName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_ranking_qa.sales_volume
     *
     * @mbggenerated
     */
    private Integer salesVolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_ranking_qa.satisfaction_degree
     *
     * @mbggenerated
     */
    private Integer satisfactionDegree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_ranking_qa.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_ranking_qa.id
     *
     * @return the value of sales_ranking_qa.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_ranking_qa.id
     *
     * @param id the value for sales_ranking_qa.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_ranking_qa.ranking_type_id
     *
     * @return the value of sales_ranking_qa.ranking_type_id
     *
     * @mbggenerated
     */
    public String getRankingTypeId() {
        return rankingTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_ranking_qa.ranking_type_id
     *
     * @param rankingTypeId the value for sales_ranking_qa.ranking_type_id
     *
     * @mbggenerated
     */
    public void setRankingTypeId(String rankingTypeId) {
        this.rankingTypeId = rankingTypeId == null ? null : rankingTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_ranking_qa.sale_consultant_id
     *
     * @return the value of sales_ranking_qa.sale_consultant_id
     *
     * @mbggenerated
     */
    public String getSaleConsultantId() {
        return saleConsultantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_ranking_qa.sale_consultant_id
     *
     * @param saleConsultantId the value for sales_ranking_qa.sale_consultant_id
     *
     * @mbggenerated
     */
    public void setSaleConsultantId(String saleConsultantId) {
        this.saleConsultantId = saleConsultantId == null ? null : saleConsultantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_ranking_qa.sale_consultant_name
     *
     * @return the value of sales_ranking_qa.sale_consultant_name
     *
     * @mbggenerated
     */
    public String getSaleConsultantName() {
        return saleConsultantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_ranking_qa.sale_consultant_name
     *
     * @param saleConsultantName the value for sales_ranking_qa.sale_consultant_name
     *
     * @mbggenerated
     */
    public void setSaleConsultantName(String saleConsultantName) {
        this.saleConsultantName = saleConsultantName == null ? null : saleConsultantName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_ranking_qa.sales_volume
     *
     * @return the value of sales_ranking_qa.sales_volume
     *
     * @mbggenerated
     */
    public Integer getSalesVolume() {
        return salesVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_ranking_qa.sales_volume
     *
     * @param salesVolume the value for sales_ranking_qa.sales_volume
     *
     * @mbggenerated
     */
    public void setSalesVolume(Integer salesVolume) {
        this.salesVolume = salesVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_ranking_qa.satisfaction_degree
     *
     * @return the value of sales_ranking_qa.satisfaction_degree
     *
     * @mbggenerated
     */
    public Integer getSatisfactionDegree() {
        return satisfactionDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_ranking_qa.satisfaction_degree
     *
     * @param satisfactionDegree the value for sales_ranking_qa.satisfaction_degree
     *
     * @mbggenerated
     */
    public void setSatisfactionDegree(Integer satisfactionDegree) {
        this.satisfactionDegree = satisfactionDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_ranking_qa.create_time
     *
     * @return the value of sales_ranking_qa.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_ranking_qa.create_time
     *
     * @param createTime the value for sales_ranking_qa.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}